### ISSUE TITLE
implicit `ImageWriter` 2.1.1 -> 2.1.3

### ISSUE THREAD

**Issue by agebhar1** [sksamuel/scrimage#100]
Hi,

first, thanks for your library! 

After upgrade from v2.1.1 to 2.1.3 we run into an issue of the file size for generated/saved images via `Image.output(...)`. The file size blown up. We **did not provide** an explicit `ImageWriter`. 

After some research it seems in version 2.1.1 the implicit `ImageWriter` is from `PngWriter`'s companion object `apply` method which forces [MaxCompression](https://github.com/sksamuel/scrimage/blob/2.1.1/scrimage-core/src/main/scala/com/sksamuel/scrimage/nio/PngWriter.scala#L83). On the other side version > 2.1.1 (within commit [Updated readme for image io](8305038dbc6cf62dabf10f6422308375f43f9280)) `ImageWriter`'s companion object define implicit  a instance of `PngWriter` but as [NoCompression](https://github.com/sksamuel/scrimage/blob/8305038dbc6cf62dabf10f6422308375f43f9280/scrimage-core/src/main/scala/com/sksamuel/scrimage/nio/ImageWriter.scala#L15) which seems counter intuitive.

Should the default `ImageWriter` be an `MaxCompression` instead of `NoCompression`?

**Comment by sksamuel** [comment]
I think it probably should be MaxCompression yes.

**Comment by agebhar1** [comment]
Pretty fast answer ... 

If it's okay, i can provide a merge request with this oneliner and a suitable test case.

Best Andreas

**Comment by sksamuel** [comment]
Yes please.
