### ISSUE TITLE
Crop issue

### ISSUE THREAD

**Issue by azickh** [sksamuel/scrimage#104]
Hi,
When creating small sizes lost quality.

`def crop(content: Array[Byte], width: Int, height: Int) = Future {`
`val image = Image(content)`
`implicit val writer = JpegWriter.NoCompression`
`image.cover(width, height).bytes`
`}`

**Comment by sksamuel** [comment]
Do you have an example image?

**Comment by azickh** [comment]
![stksw26ylo](https://cloud.githubusercontent.com/assets/13938624/13755260/2c15600a-ea3c-11e5-9b20-10c82e96033e.jpg)

**Comment by sksamuel** [comment]
I did this:

 val image = Image.fromResource("/issue104.jpg")
    implicit val writer = JpegWriter.NoCompression
    image.cover(100, 100).output("cover.jpg")

![cover](https://cloud.githubusercontent.com/assets/743706/13936327/c8b988e6-efb4-11e5-810c-aaf7589574ca.jpg)

**Comment by sksamuel** [comment]
![cover](https://cloud.githubusercontent.com/assets/743706/13936343/ee64df14-efb4-11e5-9af8-f1616efab669.png)

Png version

**Comment by azickh** [comment]
Hi sksamuel
Sorry, a long time did not respond.
convert -resize 100x100^ -gravity center -crop 100x100+0+0 issue104.jpg cover.jpg
![cover](https://cloud.githubusercontent.com/assets/13938624/14058683/4dc5870e-f34a-11e5-8a88-eff3910025a1.jpg)

**Comment by sksamuel** [comment]
Looks the same ?

**Comment by azickh** [comment]
Ok, almost looks the same, but with 100 quality not the same.
`convert -resize 100x100^ -gravity center -crop 100x100+0+0 -quality 100 issue104.jpg cover.jpg`
![cover_100](https://cloud.githubusercontent.com/assets/13938624/14132455/92f2a650-f65f-11e5-860d-694748266d1f.jpg)
