### ISSUE TITLE
GifWriter feature

### ISSUE THREAD

**Issue by cranst0n** [sksamuel/scrimage#105]
Is it possible to write a series of Image's to a GIF without closing the output stream? Looks like it's not possible at the moment.

Use case is generating a lot of images and not wanting to hold them all in memory. It would be nice to have the ability to:

1. Open a gif writer
2. Write a set of images from within some kind of loop
3. Close the gif writer at the end.

**Comment by sksamuel** [comment]
Seems like a good feature.

**Comment by cranst0n** [comment]
Sorry I meant to share this earlier but went on leave and forgot about it. I created an offshoot of `GifSequenceWriter` that accomplishes what I originally suggested:

https://gist.github.com/cranst0n/b4f9af8b657bd7c6e434f8c80d7640de

Feedback welcome and I'd be happy to turn this into a PR if you think it's an implementation you can live with.

**Comment by sksamuel** [comment]
Yes, looks good, be happy to merge that.
