### ISSUE TITLE
Jpeg orientation handling problem

### ISSUE THREAD

**Issue by akitaylor** [sksamuel/scrimage#109]
Hi!

It might be a problem deeper than the scope of this library, but certainly a problem.

I noticed that sometimes Jpeg pictures are flipped vertically when manipulating it with scrimage. Even if I do nothing else but open it and save, for example:
val img = Image.fromPath(Paths.get("d:/temp/pict/IMG_20160715_090541.jpg"))
img.output("d:/temp/pict/output.jpg")(JpegWriter(compression = 75, progressive = false))

In other cases it works fine. It turned out that the problem occures when the jpeg orientation is 3.
I used exiftool to identify the orientation:
`d:\temp\pict>exiftool.exe -Orientation -n IMG_20160715_090541.jpg`
`Orientation                     : 3`

In this case the output is flipped (not rotated), which is strange. 

Below you can find an example input file:
![img_20160715_090541](https://cloud.githubusercontent.com/assets/8057431/16866977/5bfec9b2-4a6f-11e6-8c38-ec255a59bc60.jpg)

And here is the output:
![output](https://cloud.githubusercontent.com/assets/8057431/16866998/82859fd4-4a6f-11e6-94ff-520d0d95db60.jpg)

Note, that you might have to view the input picture in full resolution to see the real problem because the github thumbnail image also seems to handle orientation in a wrong way. I tried multiple windows image editor and they work fine.

Thanks,
Akos

**Comment by sksamuel** [comment]
Fixed in 62f19e59034291afc85f96599b963930188f6c05
