### ISSUE TITLE
Image from stream should not check for availability

### ISSUE THREAD

**Issue by zifeo** [sksamuel/scrimage#110]
[Image.scala#L856](https://github.com/sksamuel/scrimage/blob/0d26c9c80c7dfca3235353af8ac56daa6340f28f/scrimage-core/src/main/scala/com/sksamuel/scrimage/Image.scala#L856) is potentially an issue as `available` is not required to be redefined. 
From the documentation of `InputStream`:
> Note that while some implementations of {@code InputStream} will return the total number of bytes in the stream, many will not.

Also, do you plan to have a `from` for streams (`akka` for instance)?

**Comment by sksamuel** [comment]
Good point, that should be removed. As for Akka, I don't want to introduce a dependency on akka just for a `from` method, it should be fairly simple to add it in your code base (or is it not?)

**Comment by zifeo** [comment]
Thanks for getting back. This makes sens. For the moment I use the following snippet but I was wondering if there was a better interface possible.
```scala
val source: Source[ByteString, Any]
val stream = source.runWith(StreamConverters.asInputStream(10.seconds))
val image = ImageReader.fromStream(stream)
```

**Comment by sksamuel** [comment]
I've never used Akka streams I'm afraid.
