### ISSUE TITLE
WebP support

### ISSUE THREAD

**Issue by skylve** [sksamuel/scrimage#111]
It would be really nice to see WebP format (Reader & Writer) in Scrimage.
Since WebP is a C lib, it could be in its own sub module or added in `scrimage-io-extra`.

https://bitbucket.org/luciad/webp-imageio is a good place to start, but the repo hasn't been updated since a long time.

I don't really know how we could package it, maybe asking the user to download the proper `.so`, `.dylib` or `.dll` or find a way to include it in the project (e.g `protocjar` with protobuf executable).

**Comment by sksamuel** [comment]
It looks like the Java one is nothing but a simple wrapper around the c library.

**Comment by sksamuel** [comment]
I'd never heard of webp before it seems really good have just read up on it.

**Comment by sksamuel** [comment]
To be fair, if it hasn't caught on by now after 6 years, looks like it's a bit dead in the water.

**Comment by skylve** [comment]
I wouldn't say it's dead in the water. It's used by many companies, including Google and Facebook, when the client can support it (http://caniuse.com/#feat=webp). Firefox and Safari support is on the way (https://bugzilla.mozilla.org/show_bug.cgi?id=856375).

WebP (including animated webp) and WebM (for videos) really improved the speed of many websites and I think the way to go when the client can support it.

Other alternatives are format like JPEG-XR or JPEG2000 (that I never tried) and I am not sure they are used as much as WebP is.

**Comment by sksamuel** [comment]
I just mean that 6/7 years on and Google have not realized a pure Java implementation of the protocol. I think that until they do (if they do) it's not really a wide enough format to warrant inclusion by default. It should be easy enough to create your own module though as an add on.
