### ISSUE TITLE
New feature request, rotate by X degrees

### ISSUE THREAD

**Issue by jgonian** [sksamuel/scrimage#119]
The current API supports `rotateRight` and `rotateLeft` but does not support a more generic `rotate(angle: Double)` meaning that if you want to rotate a picture by 180 degrees you have to rotate left (or right) twice. 

It would be nice if the library supports a way to rotate by X degrees.

**Comment by sksamuel** [comment]
There is a `rotateRadians` radians method on ImmutableImage that will do what you want.
