### ISSUE TITLE
Class path contains multiple SLF4J bindings

### ISSUE THREAD

**Issue by jimfleming** [sksamuel/scrimage#12]
I'm running into a conflict with the logger dependency included with scrimage. Specifically:

```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/jim/.ivy2/cache/org.slf4j/slf4j-log4j12/jars/slf4j-log4j12-1.6.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/jim/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.0.13.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
```

The note at the url is relevant:

> Embedded components such as libraries or frameworks should not declare a dependency on any SLF4J binding but only depend on slf4j-api. When a library declares a compile-time dependency on a SLF4J binding, it imposes that binding on the end-user, thus negating SLF4J's purpose. When you come across an embedded component declaring a compile-time dependency on any SLF4J binding, please take the time to contact the authors of said component/library and kindly ask them to mend their ways.

I have about 2 weeks experience with Scala so I may be missing something but thought I'd drop this note here, just in case.

Also, just want to say that scrimage is an awesome project and easy to work with. Thank you!

EDIT Going with the solution here for a quick-fix: http://stackoverflow.com/questions/10958215/how-to-exclude-commons-logging-from-a-scala-sbt-slf4j-project

**Comment by harmboschloo** [comment]
The SLF4J binding is still showing up for the scrimage-webp module.

**Comment by sksamuel** [comment]
I don't see any binding in the dependencies. What are you seeing the logs ? @harmboschloo
