### ISSUE TITLE
Expose mutable methods for performance-critical code

### ISSUE THREAD

**Issue by wuservices** [sksamuel/scrimage#123]
It'd be great if you could access things like `overlayInPlace` for code where you want to intentionally mutate to avoid copying. While I've just gone back to using Graphics2D directly, the scrimage syntax is much more readable take takes care of creating and disposing of a graphics in a consistent way.

I'd love to do something like `Image.wrapAwt(image).overlayInPlace(otherImage)`.

I see that Mutableimage was removed in v2 so is this just against the scrimage immutable philosophy? Could there be a opt-in way to go mutable? `wrapAwt` already allows you to mutate so being able to do more would be great.

**Comment by sksamuel** [comment]
If you use 4.0.x then the methods on MutableImage are public.
