### ISSUE TITLE
Publish for Scala 2.12.1

### ISSUE THREAD

**Issue by phdoerfler** [sksamuel/scrimage#126]

**Comment by IntelligyScience** [comment]
Thanks :)

**Comment by sksamuel** [comment]
The existing 2.12 release should work fine with 2.12.1 ?

**Comment by phdoerfler** [comment]
Sorry for getting back so late to you. I didn't know about the 2.12 release. You might want to update the readme, because it says:

> Scrimage is cross compiled for scala 2.11 and 2.10.

and:

> Latest Release: 2.1.5

**Comment by yzhong52** [comment]
@sksamuel should update the readme and close this issue?

**Comment by sksamuel** [comment]
Thanks I've updated the readme.
