### ISSUE TITLE
Twice close stream of pngwriter

### ISSUE THREAD

**Issue by jilen** [sksamuel/scrimage#135]
One in `Using`, another in `PngWriter`, this may cause error while writing file to `ZipFileSystem`

**Comment by sksamuel** [comment]
I can't see where writer.close is called by the using block. Can you point me ?

**Comment by jilen** [comment]
https://github.com/sksamuel/scrimage/blob/master/scrimage-core/src/main/scala/com/sksamuel/scrimage/Using.scala#L9

**Comment by sksamuel** [comment]
Version 4 no longer closes the stream twice.
