### ISSUE TITLE
Alphamask

### ISSUE THREAD

**Issue by Fapfood** [sksamuel/scrimage#136]
Is there any way to apply alphamask to an image? I know I can overlay or underlay other picture but how can I change transparency in given one? E.g. compose two image in specific way using alphamask.

**Comment by sksamuel** [comment]
See test showing alphamask in action:
https://github.com/sksamuel/scrimage/blob/master/scrimage-filters/src/test/kotlin/com/sksamuel/scrimage/filter/AlphamaskTest.kt
