### ISSUE TITLE
Merge Images

### ISSUE THREAD

**Issue by benqua** [sksamuel/scrimage#137]
Hi,

Is it possible to merge to images? 
I have two images A and B and would like to output an image that is made of A and B side by side. Is that possible with scrimage? Couldn't find anything in the documentation.

**Comment by sksamuel** [comment]
`val image = Image(1000,500).overlay(0,0,imagea).overlay(500,0,imageb)`

**Comment by benqua** [comment]
I will try that, thank you.

**Comment by benqua** [comment]
Thanks, works perfectly. For the record, the arguments are in the wrong order in overlay (it is overlay(imagea,0,0).

By the way, is the a scaladoc somewhere? I couldn't find the doc.
