### ISSUE TITLE
"Broken" JPG output

### ISSUE THREAD

**Issue by markuslamm** [sksamuel/scrimage#138]
Hi!
I'm trying to use your library for scaling jpg images in a zip file.
For testing purposes all images are the same, the output for `file test1.jpg` is:

JPEG image data, JFIF standard 1.01, resolution (DPCM), density 28x28, segment length 16, baseline, precision 8, 1920x1200, frames 3.

Unfortunately the resulting image looks like this:

![scaled_too-big_1](https://user-images.githubusercontent.com/1075906/29617161-2d7bb206-8814-11e7-97a8-2dd5c7f885b5.jpg)

A `file scaled_test1.jpg` results in:

JPEG image data, JFIF standard 1.02, aspect ratio, density 1x1, segment length 16, baseline, precision 8, 940x587, frames 3

The scaling works perfect, but the result isn't that good...;)

The code I'm using is:

```
def scaleIfNecessary(maxX: Int, maxY: Int, bytes: Array[Byte]): Array[Byte] = {
    val original = Image(bytes)
    val result = if(original.width > maxX || original.height > maxY) {
      original.bound(maxX, maxY)
    } else {
      original
    }
    result.bytes(JpegWriter.NoCompression)
  }
```

Do you have any ideas or do I missed something?
Thanks in advance, and great work btw...

**Comment by sksamuel** [comment]
Do you have the input ?

**Comment by markuslamm** [comment]
Do you mean

```
var zis : ZipInputStream = null
val bos : ByteArrayOutputStream = new ByteArrayOutputStream()
var zos : ZipOutputStream = null
    try {
      zis = new ZipInputStream(new ByteArrayInputStream(Base64.getDecoder.decode(zip.get.data)))
      zos = new ZipOutputStream(bos)
      var ze : ZipEntry = zis.getNextEntry
      while(ze != null) {
        val buffer = new Array[Byte](1024)
        var len = zis.read(buffer)
        ...
        val nze = new ZipEntry("scaled_" + ze.getName)
        zos.putNextEntry(nze)
        val imageComplete = ArrayBuffer.empty[Byte]
        while(len > -1) {
          imageComplete ++= buffer
          //zos.write(buffer, 0 , len)
          len = zis.read(buffer)
        }
        val imageScaled = ImageScaleHelper.scaleIfNecessary(940, 940, imageComplete.toArray)
        zos.write(imageScaled, 0 , imageScaled.length)
        zos.closeEntry()
        ze = zis.getNextEntry
      }
    } finally {
      zis.closeEntry()
      zis.close()
      zos.close()
    }
```

**Comment by sksamuel** [comment]
I mean the actual image you're trying to scale.

**Comment by markuslamm** [comment]
I just figured out, that the problem seems to be my implementation of processing, scaling the entries and writting back the Zip file. The `scaleIfNecessary` method works perfect using the bytes of just a single image not from a Zip file. But here is a single entry:

![too-big_1](https://user-images.githubusercontent.com/1075906/29651147-7789208c-889f-11e7-8df3-a3d48cbec745.jpg)
