### ISSUE TITLE
Make it clearer how to use scrimage-formats-extra to read twelve monkey supported formats

### ISSUE THREAD

**Issue by Joseph-Hui** [sksamuel/scrimage#142]
Hi,

I want to scale down some BMP data URIs in my program. I browsed the sources but I couldn't find any code is related to BMP. Is BMP support implemented?

**Comment by lanceon** [comment]
Same question. 

There's no BMP writer implementation although it is mentioned to be available: `Thescrimage-io-extra package brings in readers/writers for less common formats such as BMP Tiff or PCX`

Should doc be updated?

**Comment by sksamuel** [comment]
If 12 monkeys supports it then it should be supported as scrimage uses that library for BMP support.

https://github.com/haraldk/TwelveMonkeys

**Comment by sksamuel** [comment]
Added tests for this. You can just add `scrimage-formats-extra` to you build and it should just work. See https://github.com/sksamuel/scrimage/blob/a128373374cc0d2ff1cd9bf4b11b1f61628d7af5/scrimage-formats-extra/src/test/kotlin/com/sksamuel/scrimage/io/TwelveMonkeysFormatsTest.kt
