### ISSUE TITLE
average value of pixels?

### ISSUE THREAD

**Issue by philipjss** [sksamuel/scrimage#158]
Hello,

I would like to compute the average value of the pixels in an image. To be more precise, I need to average the pixels in each of a region of an image (a square region obtained by partitioning the image using a grid), but that's just a special case, so at the moment I am just interested in doing it for a whole image.

Is there something in scrimage that I can use to do this?

I think it needs to add the r, g and b components of each pixel (https://forum.processing.org/two/discussion/15573/get-the-average-rgb-from-pixels), and take the alpha into account too, and maybe ideally even square the components before adding them and taking the square root after adding them (https://medium.com/@kevinsimper/how-to-average-rgb-colors-together-6cd3ef1ff1e5.

Can you please tell me if there is something in scrimage that I can use to do this averaging?

I see that in scrimage there is this code for averaging pixels (though it doesn't take alpha into account): https://github.com/sksamuel/scrimage/blob/master/scrimage-filters/src/main/java/thirdparty/jhlabs/image/PixelUtils.java#L130

Is there similar code that averages a collection of pixels?

I also see that in scrimage there is https://github.com/sksamuel/scrimage/blob/master/scrimage-core/src/main/java/com/sksamuel/scrimage/composite/AverageComposite.java. This looks related, but is not quite what I need, as it takes the average of two images, rather than the average across an image.

Can you think of anything in scrimage that could do the trick?

Thank you in advance for your help,

Philip Scwharz

**Comment by sksamuel** [comment]
Take a look at ImmutableImage.average()

**Comment by philipjss** [comment]
@sksamuel thanks for looking into this 👍
