### ISSUE TITLE
Release new version to Maven Central

### ISSUE THREAD

**Issue by borice** [sksamuel/scrimage#159]
Hello.  

Just curious whether you have any plans of releasing a new version to Maven Central anytime soon? 

Thank you for all your work!

**Comment by fagossa** [comment]
@sksamuel Do you need some help for the cross compilation? 2.12 and 2.13?

**Comment by sksamuel** [comment]
I have released 4.0.0-BETA1 to maven. I have converted many of the classes to Java but mostly works in the exact same way.
