### ISSUE TITLE
Attempting to scale a tiny (e.g., 1px) image leads to ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by JustAHappyKid** [sksamuel/scrimage#162]
Apologies in advance for a quick/sloppy bug-report and minimal testing to see how far this problem extends (e.g., does it occur with 2x2-pixel images?) and whether it has not been fixed already in `master` (whereas I'm on v2.1.8).

Long story short, if you try to scale up (irrational it may be) a 1x1-pixel image to, say, 80-pixels wide...

    scrimage.Image(contentAsBytes).scaleToWidth(80)

...you'll get an `ArrayIndexOutOfBoundsException`. [Attached is an image (1x1-pixel)](https://user-images.githubusercontent.com/20557/41186513-c96ac0f0-6b65-11e8-9ac4-a4acf6d309d9.gif) that can be used to reproduce the problem. Raising an exception might make sense, but something more descriptive might be helpful -- e.g., a custom `InvalidOperationError` for example.

If this issue hasn't already been addressed and patches are welcomed, I could try to find time to take a stab at a patch and/or a test-case.

Thanks.

**Comment by JustAHappyKid** [comment]
P.S. [This merge](https://github.com/sksamuel/scrimage/pull/127) looks like it could possibly be related.

**Comment by icl7126** [comment]
I have the same problem now.
I use 1x1 GIF image:
data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7

Is there some minimum supported resolution?
