### ISSUE TITLE
get bytes issue

### ISSUE THREAD

**Issue by cottinisimone** [sksamuel/scrimage#164]
Hello @sksamuel ,
Not sure at all this is a real issue or if there's a workaround but i'm experiencing this issue:

```
   Image.fromFile(new File("whateverimage.png")).max(400, 400).bytes(PngWriter()).length

   val destFile: File = Image.fromFile(new File("whateverimage.png")).max(400, 400).output(new File("test/hello.png"))
   Image.fromFile(destFile).bytes(PngWriter()).length
```

I have that the first lenght call returns to me a different length value than the second one.

I'm using the latest version.
Thank you in advance

**Comment by sksamuel** [comment]
The number of bytes in PNG output isn't the same as the number of pixels. It can vary depending on the image / compression factor.

**Comment by sksamuel** [comment]
Yeah so the issue is in the output stage you write it out as a jpeg, which subtly changes the image as it's a lossy format. So when you read it back in and write it back out as png its not quite the same image.
