### ISSUE TITLE
Image.bytes should be inverse of Image.apply

### ISSUE THREAD

**Issue by dmurvihill** [sksamuel/scrimage#165]
Currently `Image.bytes` defaults to writing out with a `PngWriter`. As a result, this function, which intuitively should be an identity function, will instead transcode to PNG:

```scala
def thereAndBackAgain(imgIn: Array[Byte]): Array[Byte] = Image(imgIn).bytes
```

For instance, if `imgIn` is a JPEG then `thereAndBackAgain` will explode the size of the file.

**Comment by sksamuel** [comment]
When you write out to bytes you have to have some kind of format. So it's either JPEG or PNG or whatever. The library just picks PNG as the default.
