### ISSUE TITLE
Expose Image.mapInPlace to allow user-defined filters

### ISSUE THREAD

**Issue by jgibson2** [sksamuel/scrimage#166]
Currently, `Image.mapInPlace` is defined with a `protected[scrimage]` tag. This does not allow, with the current Filter trait, the ability to mutate the image in place and create user-defined Filters. It would be useful to expose this functionality to the user to allow for easy extension of filters. Another possible way of providing this functionality would be to change the signature of `Filter.apply` to `def apply(image: Image): Image` and the implementation of `Image.mapInPlace` to return `this` instead of `Unit`.

**Comment by sksamuel** [comment]
If you use 4.0.0 then the mutable methods are public.
