### ISSUE TITLE
Jpeg orientation handling problem (2)

### ISSUE THREAD

**Issue by yzhong52** [sksamuel/scrimage#167]
We saw this [issue](https://github.com/sksamuel/scrimage/issues/109) and also this [fix](https://github.com/sksamuel/scrimage/commit/62f19e59034291afc85f96599b963930188f6c05), but however, we still notice that some images are not rotated properly. This is such an image: 

https://user-images.githubusercontent.com/3712071/45652493-c822eb00-baa2-11e8-9cea-fff0099a1837.jpg

We try checking the value of the `orientationTag` and there are 3 tag values: 

```
List(
    Tag(Orientation,274,8,Left side, bottom (Rotate 270 CW)),
    Tag(White Balance Fine Tune Value,274,0,0),
    Tag(Orientation,274,8,Left side, bottom (Rotate 270 CW))
)
```

Because of `Tag(White Balance Fine Tune Value,274,0,0)`, the code was not able to detect the orientation properly. 

From this image above, it seems that it is not enough to determine that `type == 274` is for rotations. Any thoughts on this @sksamuel ?

**Comment by yzhong52** [comment]
FYI: just a follow-up, we ended up fixing this issue by patching the `reorient` function:

```
  // The version of this method in scrimage fails when images have tags of type 274
  // that aren't actually orientation tags, which happens occasionally.
  // It seems to happen particularly with Sony cameras
  def reorient(image: Image): Image = {
    val orientationTags = image.metadata.tagsBy(metadata => {
      metadata.`type` == 274 && metadata.name.toLowerCase == "orientation"
    })
    if (orientationTags.map(_.rawValue).toSet.size == 1) {
      orientationTags.head.rawValue match {
        // Normal
        case "1" => image

        // Flip horizontally
        case "2" => image.flipX

        // Rotate 180 degrees
        case "3" => image.rotateLeft.rotateLeft

        // Rotate 180 degrees and flip horizontally
        case "4" => image.rotateLeft.rotateLeft.flipX

        // Rotate 90 degrees clockwise and flip horizontally
        case "5" => image.rotateRight.flipX

        // Rotate 90 degrees clockwise
        case "6" => image.rotateRight

        // Rotate 90 degrees anti-clockwise and flip horizontally
        case "7" => image.rotateLeft.flipX

        // Rotate 90 degrees anti-clockwise
        case "8" => image.rotateLeft

        // Unknown, keep the original image
        case _ => image
      }
    } else {
      image
    }
  }
```

That's a little bit hacky to do `metadata.name.toLowerCase == "orientation" `, but it is working for us.

**Comment by sksamuel** [comment]
Thanks, I've taken your solution and used it in the codebase.
