### ISSUE TITLE
Copied image has a slightly different set of pixel values than original image

### ISSUE THREAD

**Issue by hanif-shaikh** [sksamuel/scrimage#175]
A - Take an image.
B - Modify its pixel colors (RGBA values)
C - Copy Image

The resulting copied image (C)  has pixel color values different than the original image (B).
Copy image works fine when you do not tamper with the pixel colors or if the modifications are nominal.

**Comment by aditiagarwal34550** [comment]
check if you copied it in ARGB or in RGB it should be same.
Are you talking about some code you have used to copy an image from this repo?

**Comment by sksamuel** [comment]
I've added a test case for this and it seems good (4.0.0 beta).
