### ISSUE TITLE
Could you please add support for Scala 13?

### ISSUE THREAD

**Issue by emrekanca** [sksamuel/scrimage#179]
Hi
I need to use Scala 13 in my project.
Could you please support that version?

**Comment by reibitto** [comment]
I see that 2.13.0 is in `crossScalaVersions`:
https://github.com/sksamuel/scrimage/blob/2cf30152288287eb65d95e37db1d0885a398740f/project/Build.scala#L16

Maybe it just needs to be published? Not sure.

**Comment by manfredi-giordano** [comment]
I would also benefit from a Scala 2.13 release, even from a snapshot version. Thank you :)

**Comment by solicode** [comment]
@sksamuel Are there plans to support Scala 2.13 for the 2.x series? If you're willing to do a release, I could look into creating a PR for it (haven't looked yet to see how involved it would be though). If not, I guess I can wait for an alpha release of v3 for Scala 2.13.

**Comment by sksamuel** [comment]
Please do raise a pr

**Comment by solicode** [comment]
Alright, thanks! I created the PR: #183

**Comment by Enalmada** [comment]
Could you please cut a release with this pr to get 2.13 out?

**Comment by TimFoerster** [comment]
Any update on this?

**Comment by sksamuel** [comment]
Try 4.0.0-BETA1. It's Java internally so will work on any version of Scala. You can import com.sksamuel.scrimage.scala._ to get some scala sugar but overall the end use case is almost identical to 3.0.x.

**Comment by sksamuel** [comment]
I've released 4.0.0 final now after using the 4.0 beta successfully
