### ISSUE TITLE
IntegerComponentRaster not visible

### ISSUE THREAD

**Issue by vimalaguti** [sksamuel/scrimage#192]
https://github.com/sksamuel/scrimage/blob/6be79a81c705efea5757ec851cce562759088654/scrimage-core/src/main/java/com/sksamuel/scrimage/canvas/painters/RandomPainter.java#L4

Please do not use classes from sun.* because of http://openjdk.java.net/jeps/260 
Essentially - with jdk 9+ - such classes aren't accessible

**Comment by sksamuel** [comment]
Fixed thanks.
