### ISSUE TITLE
scala subprojects fixies

### ISSUE THREAD

**Issue by vimalaguti** [sksamuel/scrimage#193]
Hi, thank you for the great work.

Please mind that there are a few classes in scala 2-12 that are missing the package, resulting in a top-level path.

They are `Erosion` `Dilation` `GrayScale`

https://github.com/sksamuel/scrimage/blob/c87d469ff65a6b0a9189f24ea4392ebd9d13f9ef/scrimage-scala_2.12/src/main/scala/com/sksamuel/scrimage/scala/Dilation.scala#L3

Also, the use of implicit conversion in scala is discouraged. I suggest that the `RichImmutableImage` class should be an implicit class with something like that:

```scala
package object scrimage {
	implicit class RichImmutableImage(val image: ImmutableImage) extends AnyVal {
		...
	}
}
```

**Comment by sksamuel** [comment]
An implicit class just sugars to what I have, so it's no difference, but I guess it's more canoncial.

**Comment by sksamuel** [comment]
The top level scala classes are just placeholders until I move them into filters. I've moved them out of the scala modules now.

I've changed the implicit defs to be implicit classes.

**Comment by vimalaguti** [comment]
Thank you!
