### ISSUE TITLE
Jpeg writer loses image metadata

### ISSUE THREAD

**Issue by fieryphoenix** [sksamuel/scrimage#195]
JpegWriter has write implementation that skips metadata: 
`writer.write(null, new IIOImage(noAlpha, null, null), params);`
E.g. photo with _Exif_ directories is read as ImmutableImage, compressed and written into output file. Final file has not any photo related meta, including color profile.
It happens regardless ImmutableImageLoader configuration (with meta enabled), image has all meta loaded.

Proposal is to include meta into Awtmage and convert into IIOMetadata during write.

**Comment by sksamuel** [comment]
Seems good approach. PR welcome or I can do it when I have time.

**Comment by fieryphoenix** [comment]
Will try to prepare PR nearest time

**Comment by Queatz** [comment]
I saw there was a commit about this with a test added, but the writers don't use the new metadata parameter?

**Comment by sksamuel** [comment]
I couldn't get it to work, so parked it for now.
