### ISSUE TITLE
Clarifications around loading tiff

### ISSUE THREAD

**Issue by oschrenk** [sksamuel/scrimage#199]
I'm running into similar issues as #194

In the README it says:

> Scrimage supports loading and saving of images in the common web formats (currently png, jpeg, gif, tiff)

When I try to load

  https://photojournal.jpl.nasa.gov/tiff/PIA21087.tif

I get

```
com.sksamuel.scrimage.ImageParseException: java.io.IOException: Invalid GIF header.
```

Further below in the README it says

> The `scrimage-formats-extra` package brings in readers/writers for less common formats such as BMP, Tiff or PCX.

When I use the `scrimage-formats-extra` the image is loaded correctly. I do not fully understand the `tiff` format, but it seems to me that `scrimage-core` does not have full support for all variations of the `tiff` format.

Is it possible to clarify the README? Maybe  write `[...] tiff (as provided by  java.io)`? Or as a drastic measure, remove `tiff` from the first sentence?

**Comment by sksamuel** [comment]
Doc has been updated.
