### ISSUE TITLE
How to install the latest version of scrimage?

### ISSUE THREAD

**Issue by lbdremy** [sksamuel/scrimage#20]
Hello,

I'm trying to install scrimage with sbt so I declared this in my file `Build.scala`
but it seems to install only a folder containing `pom` files no `jars` folder inside.

``` scala
val appDependencies = Seq(
"com.sksamuel.scrimage" % "scrimage" % "1.3.3"
)
```

What should I do to have the jars?

Thanks for your help

**Comment by medaboumessaad** [comment]
Hi @sksamuel, thanks for this amazing library.
I'm  beginner in Scala and i'm trying to apply filters to images, so i tried to use your libraries.
Of course i found several compiling problems when i tried to compile "scrimage-filters".

I need your help please!
