### ISSUE TITLE
bytes from scrimage-scala returns Unit

### ISSUE THREAD

**Issue by dlinov** [sksamuel/scrimage#200]
Method is declared as `def bytes(implicit writer: ImageWriter): Unit` and ignores its [implementation](https://github.com/sksamuel/scrimage/blob/master/scrimage-scala_2.12/src/main/scala/com/sksamuel/scrimage/implicits/package.scala#L63) returning byte array. I think it should be changed to `def bytes(implicit writer: ImageWriter): Array[Byte]` otherwise this method is pretty useless.

**Comment by sksamuel** [comment]
Thanks, fixed and released in 4.0.4
