### ISSUE TITLE
Get rid of Kotlin std lib from scrimage-core

### ISSUE THREAD

**Issue by sshobotov** [sksamuel/scrimage#201]
Is it possible to get rid of whole Kotlin std lib dependency https://github.com/sksamuel/scrimage/blob/master/scrimage-core/build.gradle.kts#L7? It seems to be used only for this file https://github.com/sksamuel/scrimage/blob/master/scrimage-core/src/main/kotlin/com/sksamuel/scrimage/kotlin/colors.kt and I'm not sure if it worth that

**Comment by sksamuel** [comment]
Agreed

**Comment by sksamuel** [comment]
4.0.5 has been released with this change.
