### ISSUE TITLE
Is it possible to use scrimage on Android?

### ISSUE THREAD

**Issue by seriousidea** [sksamuel/scrimage#202]
Is it possible to use scrimage in an Android application?

I tried to do this, but got the following error while calling `ImmutableImage.loader()`:

> java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/imageio/ImageIO;
>         at com.sksamuel.scrimage.ImmutableImage.<clinit>(ImmutableImage.java:74)
>         at com.sksamuel.scrimage.ImmutableImage.loader(ImmutableImage.java:84)

**Comment by sksamuel** [comment]
Afraid no, because Android doesn't ship with the javax.image libraries.
