### ISSUE TITLE
.fit returning image with black background

### ISSUE THREAD

**Issue by ib-jamesp** [sksamuel/scrimage#205]
Version: 4.0.4
Kotlin: 1.3.71

I have been having issues trying to get a transparent background while resizing an image which itself has a transparent background. It was always coming back black.

When I debug I see the default in `Colors` is  `public static final RGBColor Transparent = new RGBColor(0, 0, 0, 0)` which is `black`, with alpha of 0 (or in theory transparent).

My code is pretty simple:
`
val newBytes = ImmutableImage.loader() 
                .fromBytes(imageByteArray) 
                .fit(width, height) 
                .bytes(writer)
`

Any ideas why I am seeing black instead of transparent?

**Comment by sksamuel** [comment]
Are you saving it out as a png ?

**Comment by ib-jamesp** [comment]
Apologies, I should have closed the issue. We ended up cleaning up the images provided, and for whatever reason the transparency is working!

**Comment by sksamuel** [comment]
Great!
