### ISSUE TITLE
[IllegalStateException: src must store pixels as INT but was 0] with ColorBurnComposite

### ISSUE THREAD

**Issue by caftr444333** [sksamuel/scrimage#206]
[IllegalStateException: src must store pixels as INT but was 0]

This exception is thrown at the following step
val composed = imagebird.composite(new ColorBurnComposite(1), imagebird)

How should I use ColorBurnComposite?

I used the bird image in your examples as below

    val imagebird = ImmutableImage.loader().fromFile(birdIMG)
    val composed = imagebird.composite(new ColorBurnComposite(1), imagebird)

Thanks

**Comment by sksamuel** [comment]
The source image for a blend composite must be stored using ints.
If the input image is using bytes for example, then you will need to copy it first.

Eg,

`val source = ImmutableImage.loader().fromFile(mybird).copy(BufferedImage.TYPE_INT_ARGB)`

**Comment by caftr444333** [comment]
Thank you @sksamuel it works
