### ISSUE TITLE
How can I load a gif With ImmutableImage？

### ISSUE THREAD

**Issue by LainNetWork** [sksamuel/scrimage#211]
Hello，I'm trying handle a gif file and  got all of it's frame.But all of the way I load the gif with scrimage I only got an ImmutableImage Object. It seems ImmutableImage only support a single frame?And Then I find OpenGifReader ,but It also only get the first frame of gif files.
For scrimage,open-gif dependency is in runtime scope ,so may I add open-gif to my project and use open-gif to got the frames,then handle them by scrimage,or another better way?Scrimage is a very useful lib,thank you and wait for your anwer

```java
public class OpenGifReader implements ImageReader {

   @Override
   public ImmutableImage read(byte[] bytes, Rectangle rectangle) throws IOException {
      final GifDecoder.GifImage gif = GifDecoder.read(bytes);
      ImmutableImage image = ImmutableImage.wrapAwt(gif.getFrame(0));
      if (rectangle != null) {
         image = image.subimage(rectangle);
      }
      return image;
   }
}
```

**Comment by sksamuel** [comment]
If you use version 4.0.9, which I have just released, then you can do, `OpenGifReader.readAll` which will return a list of images, one per frame.

**Comment by LainNetWork** [comment]
> If you use version 4.0.9, which I have just released, then you can do, `OpenGifReader.readAll` which will return a list of images, one per frame.

Oh，Thank you very much，It helps a lot!
