### ISSUE TITLE
build for scala 2.13

### ISSUE THREAD

**Issue by Balaram-Singh** [sksamuel/scrimage#213]

**Comment by sksamuel** [comment]
https://search.maven.org/search?q=a:scrimage-scala_2.13

**Comment by Balaram-Singh** [comment]
this fails to resolve

libraryDependencies += "com.sksamuel.scrimage" %% "scrimage-filters" % "4.0.10"

sbt repositories
maven-central: https://repo1.maven.org/maven2/

could not find it

**Comment by sksamuel** [comment]
Only the scala module is built with scala. The others are java modules.

**Comment by Balaram-Singh** [comment]
Thanks 
I have now removed %% , now using
libraryDependencies += "com.sksamuel.scrimage" % "scrimage-filters" % "4.0.10"
