### ISSUE TITLE
Wrong conversion between RGB and HSV

### ISSUE THREAD

**Issue by atk91** [sksamuel/scrimage#216]
The following code snippet
 ``` 
  val color = new RGBColor(255, 255, 255)
  val res = color.toHSV().toRGB()
  println(s"${color.red} ${color.green} ${color.blue}")
  println(s"${res.red} ${res.green} ${res.blue}")
```
prints
```
255 255 255
256 256 256
```
Which becomes an issue when trying to call `toAWT()` on `res` since 256 is not a valid value for rgb. If try the same snippet with 200 instead of 255 it will print `201 201 201` as well, however `0 0 0` remains `0 0 0`.

**Comment by sksamuel** [comment]
I have fixed this and released 4.0.12.
Thanks for the bug report!
