### ISSUE TITLE
animated gif  created by animated gif is too slow

### ISSUE THREAD

**Issue by SightStudio** [sksamuel/scrimage#222]
https://sksamuel.github.io/scrimage/animated_gif/

I tried to write an animation gif from the animation gif. ( for minimize purpose ),

with both **GifSequenceWriter** and **StreamingGifWriter**
  - by the way, GifSequenceWriter is not documented and ```finish()``` in StreamingGifWriter is deleted which is not updated.

---- 
So I ran some test codes with two writers, read the animation gif and wrote the same thing.
However, the results are slightly different from the original. ( without minimizing )

It checked out both have 34 frame. However, the test output gif is slower and larger than the original.

I left this question because I don't know if it's a bug or my mistake.

TEST ENV
- windows
- jdk 1.8 zulu

OUTPUT 
- original (229KB)
<img width = "500" src="https://user-images.githubusercontent.com/50672087/107100571-290c1300-6858-11eb-919d-87b65633a43f.gif"> 

- test output (871KB)
both writer 
<img width = "500" src="https://user-images.githubusercontent.com/50672087/107100560-1e517e00-6858-11eb-83ba-01088de643ac.gif">

here's the test code i write
```kotlin
class GifSequenceWriterTest : WordSpec({

   val bird = ImmutableImage.loader().fromResource("/animated.gif")

   "gif sequence writer" should {

     "write all frames from  animated gif -  with GifSequenceWriter"  {
         val readAll = OpenGifReader().readAll(IOUtils.toByteArray(this::class.java.getResourceAsStream("/animated.gif")))
         GifSequenceWriter().withFrameDelay(0).output(readAll.toTypedArray(), "result222.gif")
      }
   }

   "write all frames from  animated gif - with StreamingGifWriter"  {
         val frames = OpenGifReader().readAll(IOUtils.toByteArray(this::class.java.getResourceAsStream("/animated.gif")))
         val writer = StreamingGifWriter(Duration.ofSeconds(0), true)
         val gifStream: StreamingGifWriter.GifStream = writer.prepareStream("result222.gif", BufferedImage.TYPE_INT_ARGB)

         frames.forEach{ frame ->
            gifStream.writeFrame(frame, Duration.ofSeconds(0))
         }
      }
})

```

**Comment by SightStudio** [comment]
To my shame, this was my mistake.

https://support.flexitive.com/support/solutions/articles/12000025492-images-and-videos-using-gifs

![image](https://user-images.githubusercontent.com/50672087/107138231-9aca8680-6956-11eb-9830-e466c1317246.png)

post above said that If a GIFs Frame Delay is below the minimum frame delay for a browser, it will be displayed
using the Default Frame Delay.

i can't find official document for this. but since i change delay time over 0.06 seconds, it's not slowing down.

**Comment by sksamuel** [comment]
Thansk for coming back and with an update. I have updated the docs with this information.
https://sksamuel.github.io/scrimage/animated_gif/
