### ISSUE TITLE
WebP: mac binary overrides linux binary

### ISSUE THREAD

**Issue by Lermex** [sksamuel/scrimage#223]
Our software runs on Linux in prod but the devs are using Windows and Mac so we need all three platforms supported at the same time. We followed the instructions and added Mac and Windows binaries to `resources`. With those binaries in place, the library works correctly on a Mac (haven't tried Windows yet) but not on Linux because the file name of Mac and Linux WebP binaries are exactly the same and the library tries to run the Mac binary on Linux.

We're willing to contribute a fix, just want to coordinate with the maintainer and agree on what the fix should look like. Would you be ok with us adding platform-specific subdirectories to `webp_binaries`, i.e. `webp_binaries/windows`, `webp_binaries/linux`, etc?

**Comment by sksamuel** [comment]
Seems like a good approach yeah

**Comment by sksamuel** [comment]
Do you still plan on working on this ?

**Comment by SightStudio** [comment]
can i make PR for this? if this is not in progress

**Comment by sksamuel** [comment]
Yes please do.

**Comment by sksamuel** [comment]
Fixed with #225
