### ISSUE TITLE
Mandatory Kotlin libs?

### ISSUE THREAD

**Issue by melezov** [sksamuel/scrimage#224]
Since Scrimage 4.0.13, Kotlin was added as a dependency:

![image](https://user-images.githubusercontent.com/551485/115201585-c788e000-a0f5-11eb-9b55-5cb7c707bd13.png)

Was this done intentionally, or was the idea to have Kotlin in "provided" scope, so that if you're not using the library from Kotlin it should not be a dependency?

Is it safe to exclude the Kotlin dependencies or could something break when using it from another JVM language if the jars are not available in classpath (e.g. imageio-tiff)?

**Comment by sksamuel** [comment]
Seems like a bug. Kotlin should not be required.

**Comment by melezov** [comment]
Thanx for the quick reply!

Ignore the `imagei-tiff` example, I misread the dependency tree - Kotlin is being pulled in by the core library (scrimage-core from 4.0.13).

**Comment by sksamuel** [comment]
Can you try 4.0.17 just in case?

**Comment by melezov** [comment]
I did try 4.0.13-4.0.17 they're all the same. 

You can clearly see here https://repo1.maven.org/maven2/com/sksamuel/scrimage/scrimage-core/4.0.17/scrimage-core-4.0.17.pom that the dependency is on `compile` instead of `runtime`.

**Comment by sksamuel** [comment]
Yeah, I see. That's odd because the kotlin dep is set as test.
https://github.com/sksamuel/scrimage/blob/master/scrimage-core/build.gradle.kts#L13

Something else must be bringing it in.

**Comment by sksamuel** [comment]
I've released 4.0.18 and the POM looks good now.
https://repo1.maven.org/maven2/com/sksamuel/scrimage/scrimage-core/4.0.18/scrimage-core-4.0.18.pom

**Comment by sksamuel** [comment]
Did this work out for you ?

**Comment by melezov** [comment]
Hey @sksamuel. I apologise for not following up earlier.

The scrimage-core looks good now 👍, but 4.0.18 for formats-extra is still pulling in Kotlin:
https://repo1.maven.org/maven2/com/sksamuel/scrimage/scrimage-formats-extra/4.0.18/scrimage-formats-extra-4.0.18.pom

Here are the changes to the dependencies gathered after the bump from 4.0.12 to 4.0.18:
![image](https://user-images.githubusercontent.com/551485/117268620-c5de4c80-ae57-11eb-9eff-ead574164b1b.png)

Dependency tree is here, as resolved by SBT:
[dependency-tree.txt](https://github.com/sksamuel/scrimage/files/6433094/dependency-tree.txt)

**Comment by sksamuel** [comment]
Ah shucks, let me do the same for all the modules.

**Comment by sksamuel** [comment]
4.0.19 has been released with kotlin eradicated completely :)
