### ISSUE TITLE
Image is truncated

### ISSUE THREAD

**Issue by MaxGierlachowski** [sksamuel/scrimage#229]
Hey, don't know if this is the right place to write this but I am trying to transform a simple square image with the following code:

```
ImmutableImage.loader()
                    .fromFile(myfile)
                    .scaleTo(myWidth, myHeight)
                    .resizeTo(myWidth, myHeight)
                    .output(PngWriter(), targetFile)
```

By doing so I get the following exception

`com.sksamuel.scrimage.ImageParseException: Image parsing failed due to: [java.io.IOException: Image is truncated.]`

After searching the web I found some solutions, only applictable to python and not directly about scrimage.

I would like to know if I can configure scrimage somehow so this error does not occur, or some explanation why this error happens?

Thanks in advance and sorry if this is not the right place to ask ^^

**Comment by sksamuel** [comment]
Do you have the source image as well?

**Comment by MaxGierlachowski** [comment]
Hey, I am so, so sorry. It was my fault, I was loading an image from the web and saving the response into an image file. The issue was that the response was an error 500 but somehow it didn't throw an error and just saved something into the file which wasn't an image. So it was all my fault and had nothing to do with scrimage, sorry that I wasted your time.

**Comment by sksamuel** [comment]
That's no problem :)
