### ISSUE TITLE
Slow GIF Frame Writes

### ISSUE THREAD

**Issue by brys0** [sksamuel/scrimage#236]
Hey, so recently I've decided to adopt your library for one of my projects pertaining to changing the GIF dimensions and it works great!

However, is there no way to write all the updated GIF frames to memory, instead of straight to disk?

I understand the memory footprint with this choice. 

However I think it would be much more performant if you write all GIF frames to memory then write all those frames together to the DISK.

Please tell me if I'm missing something; Though, it appears it writes each frame to the file in DISK instead of frames to memory then the entire GIF to disk.

**Comment by brys0** [comment]
Additionally, I've attached an image of the code I use to create the GIF and the Speeds.
![idea64_elLQ9KEhJl](https://user-images.githubusercontent.com/35676267/144152001-2e9d5eca-b945-4dd1-aaa6-15c86d78301a.png)
 
![idea64_BidT4ic3Su](https://user-images.githubusercontent.com/35676267/144152005-400de55b-9e37-4699-b1ce-9ebaab17567e.png)

**Comment by brys0** [comment]
And. if there is a way, please make sure to document it! The GIF documentation is a fair bit lacking...

**Comment by sksamuel** [comment]
PR's always welcome for docs. Anyone can improve them :)

**Comment by sksamuel** [comment]
I've added another overload that accepts any arbitrary `OutputStream` and released 4.0.24.
https://sksamuel.github.io/scrimage/changelog/

So you should be good to write to a byte array output stream and then write that to disk yourself.

**Comment by sksamuel** [comment]
https://github.com/sksamuel/scrimage/blob/master/scrimage-tests/src/test/kotlin/com/sksamuel/scrimage/core/nio/StreamingGifWriterTest.kt#L18-L30

**Comment by brys0** [comment]
Alright! I think that does what I need, thanks so much!

**Comment by brys0** [comment]
Unless, I've gone insane it appears to be the *same* speeds... 
Am I doing something wrong? Or am I running into known issues with this sort of thing.. I'm not sure. 
![image](https://user-images.githubusercontent.com/35676267/144156140-a60e7d18-d48f-4939-ae42-e71f9411d2ea.png)
![image](https://user-images.githubusercontent.com/35676267/144156158-caaa9558-a7a1-4f91-b817-9355ca55b3cb.png)

**Comment by sksamuel** [comment]
How fast are you expecting each write to take ?

**Comment by brys0** [comment]
I would hope in memory for it take around 10-20ms

**Comment by sksamuel** [comment]
Per frame or in total ?

**Comment by brys0** [comment]
per frame

**Comment by brys0** [comment]
if faster that would be great, but I know writing to disk takes a decent chunk of time.

**Comment by sksamuel** [comment]
I can get about 20ms.
Are your source images already in the same output format, otherwise it would need to convert, say int argb to 4byte arbg.

**Comment by brys0** [comment]
Hmmm, I'm not exactly sure how to check, But its quite possible they are not. Is there a way I change the format of color to the format of the gif dynamically?

**Comment by sksamuel** [comment]
Not dynamically no, as each one might be different. You can print out image.awt().type for your sources.

Looking at your code, are you measuring the speed of cover and not the gif ?

**Comment by sksamuel** [comment]
Nevermind that last comment.

**Comment by brys0** [comment]
Alright yeah, to let you know the cover for each takes around 2-3ms so that isn't the part that takes the most time, But I can try the above and see if I get any level of performance gains.

**Comment by brys0** [comment]
Doesn't appear to make anything faster, still average around 40-60ms

**Comment by sksamuel** [comment]
Ok, try this `GifSequenceWriter(delay, true).bytes(images)`
Which is an alternative implementation. It doesn't allow you to set a delay per frame but otherwise is the same.

**Comment by brys0** [comment]
alright, thank you I hope that works! Thank you :)

**Comment by sksamuel** [comment]
If it makes a difference, I can experiment why. If it makes no difference.... we'll keep talking.

**Comment by brys0** [comment]
Lets see.. I think it is around 500ms to 1 second faster. I can double check though

**Comment by brys0** [comment]
Its around 100ms faster.

**Comment by sksamuel** [comment]
Ok, well you can just use that I guess, and I'll figure out why the difference.

**Comment by brys0** [comment]
Alright, thank you so much for your help, literally one of the best experiences I've had talking to someone here! lol

**Comment by sksamuel** [comment]
Ha :)

**Comment by sksamuel** [comment]
Don't forget a star if you haven't already !

**Comment by brys0** [comment]
Oh, for sure, you 1000% deserve my support!
