### ISSUE TITLE
Detect webp images

### ISSUE THREAD

**Issue by gipeshka** [sksamuel/scrimage#237]
Hi guys.

I am heavily using scrimage and FormatDetector is a very helpful tool for me to detect format of an image. However recently I have started working with webp images and found myself unable to use FormatDetector to detect webp.

The change was fairly simple and straightforward, first 4 bytes are RIFF and bytes 8-11 are WEBP. I was wondering if you would like to include webp detection to FormatDetector. Or maybe I am missing something and a tool like this is already available in scrimage?

Best regards

**Comment by sksamuel** [comment]
Seems like a good addition.

**Comment by gipeshka** [comment]
Created https://github.com/sksamuel/scrimage/pull/238/files, not sure if it works fine though, as I was unfortunately unable to run the check locally

**Comment by gipeshka** [comment]
@sksamuel thanks for the quick merge! Do you have an idea on when the release is going to be available? I would like to use the latest version to remove the adapter from my codebase :)

**Comment by sksamuel** [comment]
4.0.25 released!

**Comment by gipeshka** [comment]
Thanks a lot!
