### ISSUE TITLE
Pixels with alpha 0 turns black

### ISSUE THREAD

**Issue by QazCetelic** [sksamuel/scrimage#239]
I'm trying to turn the white background of an image transparent, but I'm having some issues.

This is the code I'm using. I first tried using map, but that doesn't seem to support ARGB.
```kotlin
val mutImage = MutableImage(image.awt())
for (pixel in mutImage.pixels()) {
  if (pixel.red() > 240 && pixel.green() > 240 && pixel.blue() > 240) {
    val newPixel = Pixel(pixel.x, pixel.y, 0, 0, 0, 0)
    println(newPixel)
    mutImage.setPixel(newPixel)
  }
}
this.image = mutImage.toImmutableImage()
```
The code creates this image:
![image](https://user-images.githubusercontent.com/51381523/150849839-583bc839-d6bb-43d0-b05b-844335051362.png)

The ARGB value for all the pixels is 0 when printed out (`Pixel{argb=0, x=549, y=110}`).

**Comment by sksamuel** [comment]
Do you have the original image.

**Comment by QazCetelic** [comment]
![1293](https://user-images.githubusercontent.com/51381523/151694945-918a3de3-0d62-48dd-a4e7-17f562fbf8e2.jpg)

**Comment by sksamuel** [comment]
Had a little play and figured out that your issue is that your input image type doesn't contain alpha.
So you need to change the raster to support alpha.

Something like this:

```kotlin
 val image = ImmutableImage.loader().fromResource("/issue239.jpg")
      val mutImage = MutableImage(image.copy(BufferedImage.TYPE_INT_ARGB).awt())
      for (pixel in mutImage.pixels()) {
         if (pixel.red() > 240 && pixel.green() > 240 && pixel.blue() > 240) {
            val newPixel = pixel.fullalpha().red(125).blue(0).green(0)
            mutImage.setPixel(newPixel)
         }
      }
```
