### ISSUE TITLE
Moving from PHP intervention/image to Scala Scrimage

### ISSUE THREAD

**Issue by MarErm27** [sksamuel/scrimage#248]
Hello!
I have different results for Intervention crop and Scrimage resize.
Doc says that resize is the operation most people want when they think of crop.
Here is original image:
![Star-Wars-Light-of-the-Jedi-1872x550](https://user-images.githubusercontent.com/56219126/158022662-ec038179-ad54-41fb-9ef8-6801c6d01137.png)

Scrimage Scala: 
```
val image = ImmutableImage.loader().fromFile("./temp/Star-Wars-Light-of-the-Jedi-1872x550.png")
 val croppedImage = image.resizeToHeight((rotated.width * 1.5).toInt, Position.TopCenter, Colors.Transparent.awt)
 val destinationRotatedAndCroppedFile = Paths.get("./temp/cropped", "/myImage.png")
croppedImage.output(PngWriter.MaxCompression, destinationRotatedAndCroppedFile)

```
Scrimage result:
![myImage](https://user-images.githubusercontent.com/56219126/158023273-66f25e02-4b20-43b7-82a8-6c247adee738.png)

intervention/image PHP:
```
$file = file_get_contents('Star-Wars-Light-of-the-Jedi-1872x550.png');
$image = Image::make($file);
$image = $image->crop($image->width(), $image->width() * 1.5, 0, 0);
$image = $image->stream();
file_put_contents("croppedImage.png", $image->__toString());
```
intervention/image result:
![croppedImage](https://user-images.githubusercontent.com/56219126/158022817-ae3bd50e-d9db-4b96-8f65-d249ba1dec48.png)

Is there a way to make Scrimage result identical to intervention/image?

**Comment by MarErm27** [comment]
Hello, I've changed "Colors.Transparent.awt" to "rotated.quantize(256).head.awt"
It looks more similar now
How to convert Image back to byte array?

**Comment by sksamuel** [comment]
For your first question, you are using crop with larger bounds in your PHP example - so my guess is that crop actually resizes too. In scrimage you can use resize and specify both the width and height, like your did in PHP.

For the second question, you can use a writer and call .bytes on the image.
See https://sksamuel.github.io/scrimage/io/#writing

**Comment by MarErm27** [comment]
> For your first question, you are using crop with larger bounds in your PHP example - so my guess is that crop actually resizes too. In scrimage you can use resize and specify both the width and height, like your did in PHP.
> 
> For the second question, you can use a writer and call .bytes on the image. See https://sksamuel.github.io/scrimage/io/#writing

Have I understood you?
```
 val croppedImage = image.resizeTo(rotated.width, (rotated.width * 1.5).toInt, Position.TopCenter, Colors.Transparent.awt)
```

**Comment by sksamuel** [comment]
Yep
