### ISSUE TITLE
Apple M1 issues?

### ISSUE THREAD

**Issue by sharmando** [sksamuel/scrimage#249]
I have run into issues with my M1 laptop. I wonder if it is related with the little/big endian differences with other systems.

With apple being popular amongst developers and M1 being the future of apple it would be nice to have scrimage work on M1 chips.

**Comment by sksamuel** [comment]
I don't use an M1 Mac so would need someone to PR.

**Comment by brys0** [comment]
I'm quite certain this is to be more likely a JDK or JRE type bug which will be resolved by the Oracle team themselves.

If not already, I'd adopt using the [AZUL standard for ARM64 based processors](https://www.azul.com/downloads/?os=macos&architecture=arm-64-bit&package=jdk) and see if that may fix your issue.

**Comment by xetra11** [comment]
I am using Mac M1 and no issues happened yet.
using this JDK

```/.sdkman/candidates/java/11.0.12-tem```

**Comment by sharmando** [comment]
Given confirmation of successful execution on m1 I will close this ticket and review my JDK. Thanks!
