### ISSUE TITLE
Rendering text onto an image

### ISSUE THREAD

**Issue by Cormanz** [sksamuel/scrimage#250]
Hi, how do I render text onto an image with Scrimage? I've tried to use the `RenderTextFilter` from `thirdparty.jhlabs.image.RenderTextFilter`, but I can't figure out how to use it, and I can't find documentation on it anywhere.

My goal:
- I want to be able to write text onto an image with any font at any set of coordinates.

**Comment by Cormanz** [comment]
I found a way to get it work, but it felt needlessly complicated. Would it be a bad idea to implement a method like `image.text` to simplify the process?

**Comment by sksamuel** [comment]
@Cormanz there is the Canvas classes which allow you to draw text pretty easily. Did you spot that ?

**Comment by Cormanz** [comment]
I didn't. Could you show an example?

**Comment by sksamuel** [comment]
Did you try the canvas stuff in scrimage ?
