### ISSUE TITLE
JpegWriter.NoCompression preset is misleading

### ISSUE THREAD

**Issue by satorg** [sksamuel/scrimage#255]
In fact, the `JpegWriter.NoCompression` preset does not behave the way as one could think it should. According to the code piece below, `JpegWriter` won't set neither _CompressionMode_ nor _CompressionQuality_ if the `compression` property equals to 100:
https://github.com/sksamuel/scrimage/blob/65301d8817a124d7713bc3c92c742202bb0a80bc/scrimage-core/src/main/java/com/sksamuel/scrimage/nio/JpegWriter.java#L48-L51

That basically means that `MODE_COPY_FROM_META` will be used which in turn means that the compression quality will be either taken from the metadata (if it does exist in there) or simply some default value will be used.

Moreover, it is also impossible to set the compression property to 100 in any other way – such a value will be ignored for the same reason.

**Comment by sksamuel** [comment]
Fixed in 4.0.33.
Thanks for the bug report.
