### ISSUE TITLE
Animated GIF not Compressed

### ISSUE THREAD

**Issue by BakoviDagi** [sksamuel/scrimage#256]
I am starting with a GIF that is 628kb, but after scaling each frame down 10%, it's now 2.8MB. It looks like each frame now has full pixels

```java
InputStream input = Files.newInputStream(file.toPath());
File output = new File("...");

AnimatedGif gif = AnimatedGifReader.read(ImageSource.of(input));
StreamingGifWriter writer = new StreamingGifWriter(gif.getDelay(0), gif.getLoopCount() == 0);
try (StreamingGifWriter.GifStream stream = writer.prepareStream(output, gif.getFrame(0).getType())) {
	for (ImmutableImage frame : gif.getFrames()) {
		stream.writeFrame(frame.scale(.9));
	}
} catch (final Exception e) {
	log.error(":(", e);
}
```

Test GIF: 
![k](https://user-images.githubusercontent.com/56078237/212381478-11c0585c-3bee-42fe-acbd-01f43cf0dc6a.gif)

Test Output: 
![k](https://user-images.githubusercontent.com/56078237/212381572-b94d349d-2995-418d-8e0e-c90376b91af4.gif)

**Comment by BakoviDagi** [comment]
For reference on what I mean about the frame, here is the first few frames on the original:
![image](https://user-images.githubusercontent.com/56078237/212385209-77d65055-865b-4639-9195-0fd8c0c81ef1.png)


And here is the first few frames on the output:
![image](https://user-images.githubusercontent.com/56078237/212384950-5db4f0d5-60c1-4f2e-9c4e-0c377ebbc1c1.png)

**Comment by BakoviDagi** [comment]
I was able to fix this by manually removing pixels. It would be great to make this an option in the writer though.
```java
StreamingGifWriter writer = new StreamingGifWriter(gif.getDelay(0), gif.getLoopCount() == 0);
try (StreamingGifWriter.GifStream stream = writer.prepareStream(output, gif.getFrame(0).getType())) {
	BufferedImage last = null;
	for (ImmutableImage frame : gif.getFrames()) {
		BufferedImage image = frame.scale(scale, ScaleMethod.Lanczos3).toNewBufferedImage(BufferedImage.TYPE_INT_ARGB);
		if (last != null) {
			DataBuffer iBuf = image.getRaster().getDataBuffer();
			DataBuffer lBuf = last.getRaster().getDataBuffer();
			last = copy(image);
			for (int i = 0; i < iBuf.getSize(); i++) {
				if (iBuf.getElem(i) == lBuf.getElem(i)) {
					iBuf.setElem(i, 0);
				}
			}
		} else {
			last = image;
		}
		stream.writeFrame(ImmutableImage.fromAwt(image));
	}
} 
```

I also would like to further optimize it by cropping the frame to fit the actual pixels and then setting the top/left metadata on the stream, but there's no option for setting that metadata

**Comment by BakoviDagi** [comment]
@sksamuel  Thanks! One note, is it looks like that option will be ignored if you call `writeFrame` with any options

**Comment by sksamuel** [comment]
I can do a follow up release.
