### ISSUE TITLE
WebP - embedded Versions

### ISSUE THREAD

**Issue by kbachl** [sksamuel/scrimage#259]
Since google already released 1.3.0 of their WebP libraries the embedded ones should be upgraded (https://storage.googleapis.com/downloads.webmproject.org/releases/webp/index.html).
Also it would be good to have a "versions.txt" file in the scrimage/scrimage-webp/src/main/resources/dist_webp_binaries/DIST/ folders so the version can be seen.

**Comment by sharmando** [comment]
bump

**Comment by sksamuel** [comment]
I've updated them and made the directory structure much clearer so it's obvious which versions are included.
Will release shortly.
