### ISSUE TITLE
Some Webp fail to parse

### ISSUE THREAD

**Issue by sharmando** [sksamuel/scrimage#260]
I am not sure what's different in this Webp https://i3.pureformulas.net/images/product/large/kd-ultra-90-capsules-by-arthur-andrew-medical.webp (size = 30476) but I get the following exception:

```
com.sksamuel.scrimage.ImageParseException: Image parsing failed. Tried the following ImageReader implementations:
com.sksamuel.scrimage.webp.WebpImageReader@6145370b failed due to Cannot run program "/tmp/dwebp17312374118426277146binary": error=2, No such file or directory
com.sksamuel.scrimage.nio.ImageIOReader@5d22b682 failed due to No javax.imageio.ImageReader supported this image format
com.sksamuel.scrimage.nio.PngReader@7cb13d7 failed
com.sksamuel.scrimage.nio.OpenGifReader@2f5be812 failed due to Invalid GIF header.
```

The exception happened using Scrimage 4.0.31 and using doker base image eclipse-temurin:17.0.3_7-jre-alpine. While running the same program many other webp files parse just fine.

**Comment by sksamuel** [comment]
I have added a test for this and it seems to parse fine. In addition, the error in your paste says that it cannot find the file, not that it could not parse it, see `Cannot run program "/tmp/dwebp17312374118426277146binary": error=2, No such file or directory`
So maybe that's the cause?

**Comment by sharmando** [comment]
Right, the error says it cannot find a webp binary, is it possible I need to install something and my doker base image eclipse-temurin:17.0.3_7-jre-alpine is the issue or does scrimage includes the webp binaries?

**Comment by sksamuel** [comment]
Scrimage includes them.

**Comment by sharmando** [comment]
Okay, I managed to make the test pass in my project. 
Scrimage must be checking for binaries inside my resources. After deleting `resources/webp_binaries/dwebp` (has been there since 2020) the test passes.

Thank you!
