### ISSUE TITLE
on amazon linux ,error occur

### ISSUE THREAD

**Issue by dev-xiaoyan** [sksamuel/scrimage#263]
/lib64/libm.so.6: version `GLIBC_2.29' not found

my install libc is ldd (GNU libc) 2.26

**Comment by sksamuel** [comment]
What are you doing to trigger this error?

**Comment by dev-xiaoyan** [comment]
on amazon linux server with jenkins build scripts

**Comment by Kyochi** [comment]
Same issue. Do you have some workarounds except installing this version ?

**Comment by sksamuel** [comment]
Do we have sample code? Saying it doesn't work is as vague as possible.
