### ISSUE TITLE
PNG image compression ineffective 

### ISSUE THREAD

**Issue by shrynx** [sksamuel/scrimage#267]
It seems the image compression is not working for PNG 
I have a file originally 10kb, when resized and compressed becomes 29kb.
Happens with every png file i tried

the code is quite simple 

```scala
def processImage(file: InputStream): InputStream = {
    val originalImage = ImmutableImage.loader().fromStream(file)
    val resizedImage = originalImage.scaleTo(256, 256)
    val compressedImageBytes = resizedImage.bytes(PngWriter.MaxCompression)
    new ByteArrayInputStream(compressedImageBytes)
  }
```

<details>
  <summary>original image 10kb</summary>
  
![original](https://github.com/sksamuel/scrimage/assets/4706261/2d1f48ef-5359-41b7-adfa-4ad5a5366680) 

</details>

<details>
  <summary>processed image 29kb</summary>
  
![processsed](https://github.com/sksamuel/scrimage/assets/4706261/5711e662-3a8c-40f0-8a94-f0039f165803)

</details>

seems the image compression is not working correctly

**Comment by sksamuel** [comment]
Fixed in 4.0.35
