### ISSUE TITLE
Some filters don't work for non ARGB images

### ISSUE THREAD

**Issue by ABeltramo** [sksamuel/scrimage#271]
Offending line:
https://github.com/sksamuel/scrimage/blob/0d869fcb0f9c6c4faeb2fa81de97d5c81e93f429/scrimage-filters/src/main/java/com/sksamuel/scrimage/filter/SnowFilter.java#L47

This `image.copy` will make a `new BufferedImage` that will get the filter applied instead of the originally passed `ImmutableImage` image which will remain untouched. As a quick fix I've done something like:
```java
filtered = ImmutableImage.wrapAwt(img.awt(), 2);
snow_filter.apply(filtered);
original_image.overlayInPlace(filtered.awt(), 0, 0);
```
which seems to do the trick but I'm not sure if it's the best approach.

EDIT: 
same applies for SummerFilter https://github.com/sksamuel/scrimage/blob/0d869fcb0f9c6c4faeb2fa81de97d5c81e93f429/scrimage-filters/src/main/java/com/sksamuel/scrimage/filter/SummerFilter.java#L52

OldPhotoFilter https://github.com/sksamuel/scrimage/blob/0d869fcb0f9c6c4faeb2fa81de97d5c81e93f429/scrimage-filters/src/main/java/com/sksamuel/scrimage/filter/OldPhotoFilter.java#L32

and all subclasses of PipelineFilter https://github.com/sksamuel/scrimage/blob/0d869fcb0f9c6c4faeb2fa81de97d5c81e93f429/scrimage-core/src/main/java/com/sksamuel/scrimage/filter/PipelineFilter.java#L27

**Comment by sksamuel** [comment]
Fixed in 4.0.42, thanks for the bug report.

**Comment by ABeltramo** [comment]
Thanks for fixing it and for this amazing library!

**Comment by sksamuel** [comment]
You're welcome
