### ISSUE TITLE
StreamingGifWriter#withInfiniteLoop method doesn't work correctly

### ISSUE THREAD

**Issue by ShaksterNano** [sksamuel/scrimage#272]
Setting `com.sksamuel.scrimage.nio.StreamingGifWriter#withInfiniteLoop` with the value of `false` produces a GIF that plays twice, when it should only play once.

**Comment by ShaksterNano** [comment]
This might be an issue with GIF players and not the produced GIF. Removing the GIF application extension block instead of setting the loop value to 1 in it seems to cause GIF players to correctly only play the GIF once.

**Comment by ShaksterNano** [comment]
It appears this is what [ezgif](https://ezgif.com/loop-count) does.

**Comment by sksamuel** [comment]
Fixed in 4.0.41, Thanks for bug report.
