### ISSUE TITLE
ARM (M1/M2) support for WEBP

### ISSUE THREAD

**Issue by mipastgt** [sksamuel/scrimage#276]
Hi,
as Intel macs have practically reached their end of life, it would be nice if you could add support for the new ARM (M1/M2) macs to the WEBP support.
Thanks
Michael

**Comment by sksamuel** [comment]
I don't use a mac. Do you have a link for details?

**Comment by mipastgt** [comment]
Googles tools for WEBP support can be downloaded [here](https://developers.google.com/speed/webp/download?hl=en) and I think that are the ones you are using internally too. You would just have to download the binaries for M1/M2 macs there and add them to your resources. Maybe you have to add something to your native lib extraction code too, so you can find and load these additional libs. Otherwise this should work out of the box. I also still don't have an ARM mac but if you deliver software people are more and more asking for M1/M2 support.

**Comment by sksamuel** [comment]
So [Download for macOS (arm64)](https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.3.1-mac-arm64.tar.gz) is what we need ?

**Comment by mipastgt** [comment]
Yes.

**Comment by sksamuel** [comment]
I've released 4.0.40 with support, but it's not automatic.
You need to set a system property - I've updated the docs.
In a future minor release I will flip mac-arm64 to be the default.

**Comment by mipastgt** [comment]
Wouldn't it be better to just use the standard Java properties to find out which version to use?

```
       //Operating system name
        System.out.println("Your OS name -> " + System.getProperty("os.name"));

        //Operating system version
        System.out.println("Your OS version -> " + System.getProperty("os.version"));

        //Operating system architecture
        System.out.println("Your OS Architecture -> " + System.getProperty("os.arch"));
```

**Comment by sksamuel** [comment]
Possibly, wasn't sure what the values are. I'm using constants for the OS but not the arch.

**Comment by mipastgt** [comment]
You could do it like they do it in sqlite-jdbc which contains a lot of different binaries for different platforms and architectures.
https://github.com/xerial/sqlite-jdbc/blob/master/src/main/java/org/sqlite/util/OSInfo.java

**Comment by sksamuel** [comment]
What does System.getProperty("os.arch") print out on your m1 machine ?

**Comment by mipastgt** [comment]
I don't own an M1/M2 mac myself yet but according to other sources it is "aarch64".

**Comment by sksamuel** [comment]
Looks like arm from here:

https://github.com/xerial/sqlite-jdbc/blob/master/src/main/java/org/sqlite/util/OSInfo.java#L239-L241C25

**Comment by sksamuel** [comment]
This agrees with you, https://stackoverflow.com/questions/66410522/value-of-system-getpropertyos-arch-on-m1-mac
I'll check for both.

**Comment by mipastgt** [comment]
"arm" is reported by some other platforms (I have seen raspis) but not the mac.

**Comment by sksamuel** [comment]
Yeah I'm combining  it with "is mac"
