### ISSUE TITLE
Typo in microsite

### ISSUE THREAD

**Issue by GIS-sys** [sksamuel/scrimage#283]
Good day everyone!

I don't know where to report this small mistake, so I guess I put it here

There is a typo in "SBT" section on your microsite: https://sksamuel.github.io/scrimage/quick_start/
![изображение](https://github.com/sksamuel/scrimage/assets/67117384/632e17c1-09df-4f34-b5ea-29e594b78fb9)
First dependency should be written as
```
libraryDependencies += "com.sksamuel.scrimage" %% "scrimage-core" % "$version"
```
with two "%", not one

**Comment by sksamuel** [comment]
Thanks, fixed.
