### ISSUE TITLE
WebpWriter multiThread always false?

### ISSUE THREAD

**Issue by zoff99** [sksamuel/scrimage#289]
https://github.com/sksamuel/scrimage/blob/24b63c52cdddbd02e7db70058a7d06c2cb99c457/scrimage-webp/src/main/java/com/sksamuel/scrimage/webp/WebpWriter.java#L70

should that say:

```
return new WebpWriter(z, q, m, lossless, noAlpha, true);
```

**Comment by sksamuel** [comment]
Yes. Good catch.

**Comment by zoff99** [comment]
can you publish a fix release?
