### ISSUE TITLE
Reset Stream after reading ImageMetadata

### ISSUE THREAD

**Issue by max-peroch** [sksamuel/scrimage#291]
Hello,

Is there any way to know what's the maximum amount of bytes that can be consumed from a stream in order to read the `ImageMetadata`?

I would like to be able to reset the stream after reading the metadata with `ImageMetadata.fromStream(bufferedStream)` from a `BufferedInputStream`, but the stream needs to be "marked" first.

Any idea if that's possible?

Thank you!

**Comment by sksamuel** [comment]
Not sure I follow.

**Comment by max-peroch** [comment]
Apologies for the confusion!

I would like to extract the metadata of an image **and** keep the original stream so that I can store the image somewhere along with some information about it etc. Because reading the metadata doesn't require to consume the stream entirely, I'm hoping to be able to reset the stream to its start after extracting the metadata.

Here is an example of how the `metadata-extractor` does something similar: https://github.com/drewnoakes/metadata-extractor/blob/main/Source/com/drew/imaging/FileTypeDetector.java#L137

It "marks" the amount of bytes that can be read at most, so that when done it can call ` inputStream.reset();`. That way the stream that was passed as an input can still be processed from the beginning.

Hope I make more sense!

**Comment by sksamuel** [comment]
So you want to read metadata.
Reset the stream.
Then reuse the stream to load the entire image later ?

**Comment by sksamuel** [comment]
Could you do something like:

```
in.mark(Integer.MAX_VALUE);
ImageMetadata metadata = ImageMetadata.load(new InputStreamImageSource(in));
in.reset();
```

The  parameter to mark is just how many bytes can be read before the mark is invalid. In your case you don't care, you just want to go back to the start.

**Comment by max-peroch** [comment]
Yes, that's exactly what I do! I was just wondering if that could be somehow unsafe or had a performance impact in any way etc

**Comment by sksamuel** [comment]
No, the marker parameter is just a max ahead read. So it doesn't matter.
I think you're good to go !
