### ISSUE TITLE
Png images taken in portrait on iOS device get rotated CCW 90 degrees

### ISSUE THREAD

**Issue by andrewjackman** [sksamuel/scrimage#47]
I'm using Image.cover to generate a 600x600 image from whatever image a user uploads, saving the result in S3 and then rendering the page using the resized image. If I upload a photo taken in portrait orientation on my iPhone, the resultant image after calling Image.cover(...) is rotated CCW by 90 degrees.

I seem to remember seeing issues like this on Windows, where the built-in image renderer doesn't respect the EXIF orientation data. Now I know png files don't contain EXIF data, however they can contain metadata such as orientation, and I suspect Apple must make use of this since the orientation is always correct on my Mac and iDevices.

I'm interested to hear if anyone else has had similar issues, and whether there is a well-known solution I could contribute back to this project.

**Comment by GitsMcGee** [comment]
> And maybe extends the actual loading method with one that is aware of iOS conventions.

+1!

**Comment by sksamuel** [comment]
Now that we have the metadata package in the 2.0 release, we can use that to look for orientation and correct. Any suggestions on syntax?. Maybe

`Image(bytes).reorientate`

or

`Image(bytes).autoorient`

**Comment by sksamuel** [comment]
@GitsMcGee @keeth @andrewjackman

**Comment by sksamuel** [comment]
Can one of you nice fellas supply me an iOS image as I don't own any apple devices (!)

**Comment by andrewjackman** [comment]
Here you go:

**Comment by sksamuel** [comment]
Don't see anything sorry @andrewjackman

**Comment by andrewjackman** [comment]
Yeah sorry, I replied from Mail on my phone, and It seems GitHub stripped out the image.

![img_1638](https://cloud.githubusercontent.com/assets/427903/8161007/c88263c8-136b-11e5-9d54-a90a0e430344.JPG)

**Comment by sksamuel** [comment]
So is that a landscape image that looks portrait or ...

**Comment by andrewjackman** [comment]
Portrait.

**Comment by sksamuel** [comment]
It looks portrait in that picture, so what needs to happen to it ?

**Comment by andrewjackman** [comment]
"If I upload a photo taken in portrait orientation on my iPhone, the resultant image after calling Image.cover(...) is rotated CCW by 90 degrees."

**Comment by andrewjackman** [comment]
Glad you're looking at this BTW :)

**Comment by sksamuel** [comment]
No problem, should be easy to fix tbh. Just to be clear, if I do

Image(yourfile).cover(x,y) the image will be rotated 90 degrees ?

**Comment by andrewjackman** [comment]
Yes, I just tested it.

**Comment by GitsMcGee** [comment]
Thanks for looking at this @sksamuel

**Comment by sksamuel** [comment]
@GitsMcGee @andrewjackman so it looks like its just apple being shit. They don't rotate the image, but add a metadata entry to say "this image was taken rotated".

**Comment by sksamuel** [comment]
@GitsMcGee  @andrewjackman 
In master now (and will be part of 2.0.0 final), the Image.fromStream, Image.fromResource, and Image.fromFile methods will all detect the iphone orientation and correct.

What I need now, if you're able to help, is more example files. This is because each of the 4 orientations are encoded differently and I need examples of all (so like upside down, rotated left, rotated right, normal). I only have rotate right at the moment (the flower picture that @andrewjackman kindly provided).
