### ISSUE TITLE
Performance of the new scaling version

### ISSUE THREAD

**Issue by gwenzek** [sksamuel/scrimage#49]
I modified the scaling benchmark to see how my translation to scala of the previous Bicubic scaling performed.
(ResampleOp -> ResampleOpScala)

The original result was a scala version 4x slower than the java one.
I replaced some "for" loops by "while", and moved declarations of var outside of loops.
It makes the code ugly but a bit faster.

Now it's typically 2x slower :  
 
    Testing Mortennobel Bicubic
    Time: 59820 ms
    Testing Mortennobel Bicubic in scala
    Time: 130967 ms

But the numbers above change a lot at each run. Plus my computer has only 2 core so the parrallelization isn't so effective. Could someone try to reproduce those tests
and/or suggests me other improvements I can make ?

**Comment by sksamuel** [comment]
This is nearly a year old, so parking this work.
