### ISSUE TITLE
"mixed in" color

### ISSUE THREAD

**Issue by andreykl** [sksamuel/scrimage#54]
Hello dear Stephen,

at the first of all I would like to thank you very much for writing such a good tool! I like the library, it's speed (especially for the best quality) and also I like it is native scala library. And the thing I like most of all is the API, I really like it!

I noticed a weird behaviour of library (I'm not sure it is library, but it is what i'm thinking now): sometimes it convers images very good and correctly. But sometimes I see that image has something like color mixed in it. And sometimes I even see something like rainbow instead of image. So, just colored curves, but not the image. This is a tomcat(and jetty) application. After I have restarted tomcat, images are converted correctly (or with different errors, so, behaviour will be changed). The same situation is under jetty.

Unfortunately, I was not able to create reproducing steps for you, sorry. But I have attached images with "mixed in" red color. And their originals too. 
Images were converted with next code:

```scala
im = scrimage.Image(image.data.is).fit(dim.width.is, dim.height.is)
data(im.write(scrimage.Format.JPEG)) //saving image to database
```

Please, see examples of images below.

![with-red-1](https://cloud.githubusercontent.com/assets/646992/3981980/68c685f2-2872-11e4-9882-f55746738c1d.jpeg)
![with-red-2](https://cloud.githubusercontent.com/assets/646992/3981981/68d2fdfa-2872-11e4-938b-a3bb4cf7e608.jpeg)
![foggy_forest_by_jake_stewart](https://cloud.githubusercontent.com/assets/646992/3981991/7341891e-2872-11e4-9afe-ec8b87a5e545.jpg)
![ibanez_infinity_by_jaco_kok](https://cloud.githubusercontent.com/assets/646992/3981992/734c8026-2872-11e4-850b-cf2e53bff012.jpg)

Please, let me know if I can help more.

Thanks,
Andrey.

**Comment by danny-cassidy** [comment]
I can also confirm updating the twelve monkeys dependency to 3.0.1 fixed my issue as well. Thanks for the quick response, @haraldk.
