### ISSUE TITLE
2.0 Roadmap

### ISSUE THREAD

**Issue by sksamuel** [sksamuel/scrimage#59]
@gwenzek and I have been working on new features for 1.5 but I want to be more ambitious and discuss 2.0. Please contribute to this thread with your ideas and API changes. This is just brainstorming at the moment, it doesn't mean we have to do it or will do it.

- pluggable readers and writers, release readers/writers for more esoteric formats as additional dependencies
- replace AWT raster with our raster, so we can optimize the common operations (scale/resize/rotate).
- continue the work on Canvas to wrap Graphics2D in a proper functional interface
- consider dropping mutable image, consider dropping async image in favour of users executing in their own future.

**Comment by ChrisA89** [comment]
+1 to streaming images.

**Comment by sksamuel** [comment]
2.0 is released and many of these features are now included. Anything missing / or otherwise desired can be opened as new tickets.
