### ISSUE TITLE
Resizing a png

### ISSUE THREAD

**Issue by igalbenardete** [sksamuel/scrimage#66]
Whenever I am trying to resize and position a smaller image(png) onto a bigger one(jpg), the background of the smaller png image becomes completely white blocking the bigger image ? resizeTo. fit. scle to does all the same thing. How can I resize an image without interrupting the backgorund ? Is this a problem due to the image format ?

**Comment by sksamuel** [comment]
Can you show me some sample code so I can see what you mean (you probably just need to use Color(255,255,255,255).

**Comment by sksamuel** [comment]
Closing unless you can provide sample @igalbenardete
