### ISSUE TITLE
Image comparison

### ISSUE THREAD

**Issue by igalbenardete** [sksamuel/scrimage#68]
How does the === work for comparing images ? I am trying to write tests for my image processing functions and I am trying to find the most practical way to compare images.

**Comment by gwenzek** [comment]
For the difference between == and === : 
http://stackoverflow.com/questions/10489548/scala-operator-in-scala-koans

A quick look at the code tells us that == compares the "imageState" which is a tuple:

    private[scrimage] def imageState = (width, height, awt.getType, pixels.toList)

`awt.getType` indicates whether it's a gray image or not, and if the image uses an alpha channel.
