### ISSUE TITLE
Image.SCALE_THREADS should be configurable

### ISSUE THREAD

**Issue by brianmartin** [sksamuel/scrimage#71]
https://github.com/sksamuel/scrimage/blob/42e7108c224b3fcd11915917bb185b082326f9c7/core/src/main/scala/com/sksamuel/scrimage/Image.scala#L663

**Comment by gwenzek** [comment]
IMHO it's a bit against scala philosophy which is to hide parallelization details to the programmer...
I'm curious, why do you need it ?  

And how would you like it to be implemented ? As an optional argument to the Image.scale method ?
It's quite easy to add, so if anyone agrees with you, I'll do it.

**Comment by sksamuel** [comment]
We should update it to take an ExecutionContext rather than making it's own
threads.

**Comment by sksamuel** [comment]
But we could allow people to tweak how many tasks it's broken down into.

**Comment by sksamuel** [comment]
I had a little play about on the working branch just to see how hard it would be to unify with an ExecutionContext so we can use standard Scala threading idioms.

Testing java.awt.Image.getScaledInstance() High Quality
Time: 4084 ms
Testing java.awt.Image.getScaledInstance() Fast
Time: 2352 ms
Testing ImgScalr High Quality
Time: 1078 ms
Testing ImgScalr Fast
Time: 12 ms
Testing Scrimage Bicubic
Time: 780 ms
Testing Scrimage Fast
Time: 24 ms

**Comment by sksamuel** [comment]
Before the changes:

Testing java.awt.Image.getScaledInstance() High Quality
Time: 4096 ms
Testing java.awt.Image.getScaledInstance() Fast
Time: 2507 ms
Testing ImgScalr High Quality
Time: 1081 ms
Testing ImgScalr Fast
Time: 11 ms
Testing Scrimage Bicubic
Time: 859 ms
Testing Scrimage Fast
Time: 27 ms

**Comment by brianmartin** [comment]
@sksamuel Your commit looks good to me. It would be a little easier to review with the formatting changes separated out.

I should have said in the description that the root problem I ran into was hanging on waiting for all the threads on `^c`.  It looks in your commit like you are now more explicitly handling that case.

If you're interested, you should be able to reproduce the hang on `^c` by resizing an image on a bunch of threads in parallel, then `^c`.
