### ISSUE TITLE
I can't use withCompression(x) and withMaxCompression() methods in AsyncImageWriter

### ISSUE THREAD

**Issue by jfabaf** [sksamuel/scrimage#75]
Hi,

this is my code:

imageout.writer(Format.PNG).withMaxCompression.write(fileout)

imageout is an AsyncImage.

And the compiler says:

[error] value withMaxCompression is not a member of com.sksamuel.scrimage.io.AsyncImageWriter[com.sksamuel.scrimage.io.PngWriter]
[error]                   imageout.writer(Format.PNG).withMaxCompression.write(fileout)
[error] one error found
[error] (compile:compile) Compilation failed

Is there any error in my code?
Thank you in advance.

**Comment by sksamuel** [comment]
Don't use the Async Image, it's getting deprecated anyway. I think its better now to have the image operations run inside your own execution context. I can help you with that if you post up some code.

**Comment by jfabaf** [comment]
Thank you very much.

I've just changed my code to Image instead of AsyncImage and now it works perfectly.

Thank you again!!!
