### ISSUE TITLE
Unable to write animated GIF

### ISSUE THREAD

**Issue by Snoozy** [sksamuel/scrimage#78]
When I try to resize a GIF and write it to file, all that is written is the first frame of the GIF. Is this is a bug? I am simply using `img.constrain(2000,2000).write(o, Format.GIF)`.

**Comment by sksamuel** [comment]
Doesn't support animated gifs yet I'm afraid.

**Comment by sksamuel** [comment]
We can use something like: http://elliot.kroo.net/software/java/GifSequenceWriter/GifSequenceWriter.java if anyone wants to do a PR.

**Comment by sksamuel** [comment]
In 2.1 you can do GitSequenceWriter().output(images, path) where images is a Seq of scrimage.Image
