### ISSUE TITLE
Migration guide for 1.4.x -> 2.0.x

### ISSUE THREAD

**Issue by ulejon** [sksamuel/scrimage#81]
Would be really nice with a migration guide for upgrading from 1.4.x to 2.0.x.

**Comment by sksamuel** [comment]
Absolutely, one will be done for 2.0.0 final.

**Comment by ulejon** [comment]
Sounds good. 
In the meantime, could you give me a hint of how this code should be changed when using 2.0.0-M1:

val out = new ByteArrayOutputStream()
val image: Image = Image(headerLogoStream).fit(2480, 437, position =  Position.CenterRight)
image.writer(Format.PNG).write(out)

image.writer(...) gives me a compile error

**Comment by sksamuel** [comment]
Yep.

To get a PNG output you can simply do:

val bytes = Image(header).fit(2480, 437, position =
Position.CenterRight).bytes

.bytes on the image takes a Writer typeclass, of which
PngWriter.MaxCompression is in scope by default. If you wanted to tweak it,
use jpeg or whatever,

implicit val writer = JpegWriter()....
val bytes = Image(header).fit(2480, 437, position =
Position.CenterRight).bytes

or explicitly

val bytes = Image(header).fit(2480, 437, position =
Position.CenterRight).bytes(writer)

You can also output to a file / path directly

Image(header).fit(2480, 437, position = Position.CenterRight).output(new
Path) // uses in scope implicit either png or override
Image(header).fit(2480, 437, position = Position.CenterRight).output(new
Path)(writer) // explicitly invoking

**Comment by ulejon** [comment]
Cool, thanx! 
Could you also have a look at issue #80 ?

**Comment by sksamuel** [comment]
Readmes updated. 2.0.0 is released.
