### ISSUE TITLE
AsyncImage Future control

### ISSUE THREAD

**Issue by bthibault** [sksamuel/scrimage#82]
More of a scala question problem... 

Anybody know how I can do something like this... My program is shutting down too early, what I need to do is stuff everything inside of one Future and await the result, so how can I block and wait until everything is done? 

     for (
          file <- dir.listFiles;
          image <- AsyncImage(file);
          scaled <- image.scale(0.5))
          // possibly more ops here
      {
          scaled.writer(Format.PNG).write(new File(dirOutput + file.getName))
      }

**Comment by sksamuel** [comment]
I wouldn't use the for comprehensive here as you're mixing monads. You should only use that when you have all futures, or all sequences, etc.

You can just do,

```scala
val futures = for (file <- dir.listFiles) yield {
 Future {
   val image = Image(file).scale(0.5).write(new File(dirOutput + file.getName))
 }
}
val f = Future.sequence(futures)
Await.result(f, 10.seconds)
```

This assumes you're using version 2.0.0-M2

**Comment by bthibault** [comment]
Thanks, I'll close this out. This might be a good update to the docs.
