### ISSUE TITLE
IIOException writing a JPEG on OpenJDK

### ISSUE THREAD

**Issue by avdv** [sksamuel/scrimage#84]
I wanted to upgrade to version 2.0 (thanks for your effort BTW!).

The old code works fine (version 1.4.2):

```scala
img.write(new File("/tmp/out.jpeg"), Format.JPEG)
```

Migrating the code to the new API, thusly:

```scala
val writer = JpegWriter()
img.output(new File("/tmp/out.jpeg"))(writer)
```

throws an exception using OpenJDK Runtime Environment (build 1.8.0_45-b14) but works on Oracle's JVM.

```
javax.imageio.IIOException: Invalid argument to native writeImage
  at com.sun.imageio.plugins.jpeg.JPEGImageWriter.writeImage(Native Method)
  at com.sun.imageio.plugins.jpeg.JPEGImageWriter.writeOnThread(JPEGImageWriter.java:1063)
  at com.sun.imageio.plugins.jpeg.JPEGImageWriter.write(JPEGImageWriter.java:365)
  at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageWriter.write(Unknown Source)
  at com.sksamuel.scrimage.nio.JpegWriter.write(JpegWriter.scala:41)
  at com.sksamuel.scrimage.WriteContext.write(WriteContext.scala:25)
  at com.sksamuel.scrimage.WriteContext.write(WriteContext.scala:19)
  at com.sksamuel.scrimage.Image.output(Image.scala:310)
```

According to http://stackoverflow.com/a/17845696/4432837 this is due to the fact that OpenJDK does not support JPEGs with alpha value, AFAIUI.

I understand that this is not directly scrimage's fault; but, has something changed to make it no longer work in the new version?

Seems I can work-around by explicitly specifying the type of the Image, as in `Image(bytes,  BufferedImage.TYPE_3BYTE_BGR)`.

**Comment by sksamuel** [comment]
Do you have the image you're using (save me making one).

**Comment by avdv** [comment]
Sure, here you go: http://assets.amuniversal.com/4f7bc9a06cc801301d50001dd8b71c47

**Comment by sksamuel** [comment]
So just save that as is, jpeg writer, will break? @avdv

**Comment by avdv** [comment]
Yes, as in:

```scala
import com.sksamuel.scrimage._

val in = new java.net.URL("http://assets.amuniversal.com/4f7bc9a06cc801301d50001dd8b71c47").openStream

while (in.available == 0) () // required by line below

val img = Image.fromStream(in)

val w = nio.JpegWriter()

img.output(new java.io.File("/tmp/f.jpeg"))(w) // will throw
```

**Comment by sksamuel** [comment]
No wonder I don't see this as I use Oracle's JDK. I'l install openjdk

**Comment by sksamuel** [comment]
Ok added fix. Will include in 2.0.1 and 2.1.0

**Comment by avdv** [comment]
Thanks!

BTW, would it make sense doing this only if `awt.getColorModel.hasAlpha` in order to avoid copying the image needlessly?

**Comment by sksamuel** [comment]
Ah of course, good suggestion.
