### ISSUE TITLE
PNG with transparency turns white when resized

### ISSUE THREAD

**Issue by zbeckman** [sksamuel/scrimage#85]
We have a library of PNGs that I'm generating thumbnails for:
```
Image(bytes).fit(dimensions._1, dimensions._2).writer(Format.PNG).withCompression(9).toStream
```
These images are, for example, round (like a button) with transparency.

The resulting thumbnail loses it's transparency, and has a white (square) border – all alpha is lost and converted to white.

**Comment by sksamuel** [comment]
Which version are you using ?

**Comment by zbeckman** [comment]
We are using 1.4.2:
```
	"com.sksamuel.scrimage" %% "scrimage-core" % "1.4.2",
```

**Comment by sksamuel** [comment]
Looks like it happens in 2.0.0 as well

**Comment by sksamuel** [comment]
Ha I'm an idiot myself. The background defaults to white when you do anything involving scaling. Maybe it should default to transparent, could argue either way @zbeckman

**Comment by zbeckman** [comment]
Hmm. I'm still getting a white background even after adding the transparency:
```
val transparent: RGBColor = RGBColor(255, 255, 255, 0)
Image(bytes).fit(dimensions._1, dimensions._2, transparent).writer(Format.PNG).withCompression(9).toStream
```
Am I doing that wrong?

**Comment by sksamuel** [comment]
You might as well try 2.0.2 to be sure.

**Comment by sksamuel** [comment]
And where is the byte array coming in?

**Comment by zbeckman** [comment]
Upgraded to 2.0.2 and that fixed it! Had to struggle with the API for a bit (docs are slightly out of date I think), but did get it working.

**Comment by sksamuel** [comment]
Must have been a bug in 1.4.x then. If you can let me know which docs you struggled with I'll update them.
