### ISSUE TITLE
Could not instantiate SVGImageReader

### ISSUE THREAD

**Issue by Hivemind9000** [sksamuel/scrimage#86]
Hey

I'm getting the following exception when instantiating an Image:

Could not instantiate SVGImageReader (missing support classes).
java.lang.NoClassDefFoundError: org/apache/batik/transcoder/TranscoderException
	at com.twelvemonkeys.imageio.plugins.svg.SVGImageReaderSpi.onRegistration(Unknown Source)
	at javax.imageio.spi.SubRegistry.registerServiceProvider(ServiceRegistry.java:726)
	at javax.imageio.spi.ServiceRegistry.registerServiceProvider(ServiceRegistry.java:307)
	at javax.imageio.spi.IIORegistry.registerApplicationClasspathSpis(IIORegistry.java:211)
	at javax.imageio.spi.IIORegistry.<init>(IIORegistry.java:138)
	at javax.imageio.spi.IIORegistry.getDefaultInstance(IIORegistry.java:159)
	at javax.imageio.ImageIO.<clinit>(ImageIO.java:66)
	at com.sksamuel.scrimage.Image$.<init>(Image.scala:719)
	at com.sksamuel.scrimage.Image$.<clinit>(Image.scala)

It's related to the dependency within the twelvemonkeys library on batik and jmajick. After reading a post on the twelvemonkeys repository, they say just delete the imageio-batik and imageio-jmagick jars from the classpath, however these are managed by SBT (via Ivy) as dependencies within your libraries.

Is there a way to separate out these dependencies so that these exceptions are caught in context to when you require them (I don't - just using PNGs)?

Thanks.

**Comment by sksamuel** [comment]
Are you including scrimage-io as well as scrimage-core ?

**Comment by sksamuel** [comment]
Also can you upload the image if you're able ?

**Comment by Hivemind9000** [comment]
Yes, I am using scrimage-io so I can use PngWriter. I am actually creating the image from an Array of Pixels (generated from a layer of a Neural Network system I am building). The image is still being created correctly, but am getting the runtime error as I don't have the native batik and JMagick libraries installed on my computer.

I cannot suppress them with a try/catch as they are a runtime error (not thrown at instantiation).

I guess if they are mandatory in order to use scrimage without the errors, perhaps some info and links at the bottom of the ReadMe.md might be good?

Thanks for your response (and your great library) - much appreciated.

Attached: Image representing a 50x1 output matrix from a neural net:

![slrbm](https://cloud.githubusercontent.com/assets/4607635/8399220/851f630e-1e5d-11e5-9216-7b83b879a20a.png)

**Comment by Hivemind9000** [comment]
Just in case I'm doing something wrong, here's the code I'm using the generate the images:

```
// Create images from RBM State
val imageDir = "data/output/"
PngImage.renderFromMatrix(slrbm.v, 28, 28).saveToFile(s"${imageDir}slrbm_v.png")
PngImage.renderFromMatrix(slrbm.W).saveToFile(s"${imageDir}slrbm_w.png")
PngImage.renderFromMatrix(slrbm.h).saveToFile(s"${imageDir}slrbm_h.png")
```

and

```
// Create a PNG from an Array (Matrix)
class PngImage(val rawImage: Image) {

  require (rawImage != null)

  def saveToFile(filePath: String): Unit = {
      rawImage.output(new File(filePath))
  }

}

// PngImage Singleton
object PngImage {

  // Render INDArray Matrix to a PNG Image
  def renderFromMatrix(m: INDArray, cols: Int = 0, rows: Int = 0): PngImage = {

    import org.nd4j.linalg.ops.transforms.Transforms._

    val max = abs(m).data.asDouble.max

    // Convert integer values to greyscale/RGB
    val data = m.div(max).data.asDouble.map { i => 
      val c = 127 + (127 * i).toInt
      Pixel(c, c, c, 255)
    }

    var rawImage: Image = null
    val nCols = if (cols > 0) cols else m.columns
    val nRows = if (rows > 0) rows else m.rows

    require (nCols * nRows == data.length)

    try {
      rawImage = Image(nCols, nRows, data.toArray)
    } catch {
      case e: Exception => println("Scrimage Exception Caught") // Not working
      case _: Throwable => println("Scrimage Exception Caught") // Not Working
    }

    new PngImage(rawImage)
  }

}
```

The 3 images output are attached (don't make much sense as they are the internals of the NN):

![slrbm_h](https://cloud.githubusercontent.com/assets/4607635/8399541/a1c59a1c-1e64-11e5-8416-533f1abc68be.png)
![slrbm_v](https://cloud.githubusercontent.com/assets/4607635/8399542/a1cb84f4-1e64-11e5-87ca-7fbd55c704b4.png)
![slrbm_w](https://cloud.githubusercontent.com/assets/4607635/8399543/a1cf5da4-1e64-11e5-9915-d9c4435377ab.png)

**Comment by sksamuel** [comment]
Great, I'll get that fixed. In the meantime, drop the scrimage-io package
from your build. That's only for more obscure formats, you don't need it
for PNG. I'll probably rename this to scrimage-io-extra to make it clear.

**Comment by Hivemind9000** [comment]
Dropped the scrimage-io dependency and it runs without the exceptions. Thanks again Stephen.

**Comment by sksamuel** [comment]
I've removed the batik libaries, and renamed the module to io-extra so its more clear its not needed for png.
