### ISSUE TITLE
Possible Optimization in AwtImage.fastscale

### ISSUE THREAD

**Issue by EdgeCaseBerg** [sksamuel/scrimage#87]
Hello! 

I've been enjoying your library so far, and happened to notice a place where there _might_ be an improvement. I haven't done image processing in a while though, so rather than open a pull request with the update, I figure'd I'd run it by you first and get your thoughts. 

In [AwtImage.fastscale](https://github.com/sksamuel/scrimage/blob/master/scrimage-core/src/main/scala/com/sksamuel/scrimage/AwtImage.scala#L329) you're scaling like so with drawImage: 

    protected[scrimage] def fastscale(targetWidth: Int, targetHeight: Int): BufferedImage = {
      val target = new BufferedImage(targetWidth, targetHeight, awt.getType)
      val g2 = target.getGraphics.asInstanceOf[Graphics2D]
      g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_NEAREST_NEIGHBOR)
      g2.drawImage(awt, 0, 0, targetWidth, targetHeight, null)
      g2.dispose()
      target
    }

But according to [java.net](https://today.java.net/pub/a/today/2007/04/03/perils-of-image-getscaledinstance.html#creating-scaled-instances) large image scaling can be done a bit more performant by multiple resizes. Quoting from the article:

    /**
     * Convenience method that returns a scaled instance of the
     * provided {@code BufferedImage}.
     *
     * @param img the original image to be scaled
     * @param targetWidth the desired width of the scaled instance,
     *    in pixels
     * @param targetHeight the desired height of the scaled instance,
     *    in pixels
     * @param hint one of the rendering hints that corresponds to
     *    {@code RenderingHints.KEY_INTERPOLATION} (e.g.
     *    {@code RenderingHints.VALUE_INTERPOLATION_NEAREST_NEIGHBOR},
     *    {@code RenderingHints.VALUE_INTERPOLATION_BILINEAR},
     *    {@code RenderingHints.VALUE_INTERPOLATION_BICUBIC})
     * @param higherQuality if true, this method will use a multi-step
     *    scaling technique that provides higher quality than the usual
     *    one-step technique (only useful in downscaling cases, where
     *    {@code targetWidth} or {@code targetHeight} is
     *    smaller than the original dimensions, and generally only when
     *    the {@code BILINEAR} hint is specified)
     * @return a scaled version of the original {@code BufferedImage}
     */
    public BufferedImage getScaledInstance(BufferedImage img,
                                           int targetWidth,
                                           int targetHeight,
                                           Object hint,
                                           boolean higherQuality)
    {
        int type = (img.getTransparency() == Transparency.OPAQUE) ?
            BufferedImage.TYPE_INT_RGB : BufferedImage.TYPE_INT_ARGB;
        BufferedImage ret = (BufferedImage)img;
        int w, h;
        if (higherQuality) {
            // Use multi-step technique: start with original size, then
            // scale down in multiple passes with drawImage()
            // until the target size is reached
            w = img.getWidth();
            h = img.getHeight();
        } else {
            // Use one-step technique: scale directly from original
            // size to target size with a single drawImage() call
            w = targetWidth;
            h = targetHeight;
        }
        
        do {
            if (higherQuality && w > targetWidth) {
                w /= 2;
                if (w &lt; targetWidth) {
                    w = targetWidth;
                }
            }

            if (higherQuality && h > targetHeight) {
                h /= 2;
                if (h &lt; targetHeight) {
                    h = targetHeight;
                }
            }

            BufferedImage tmp = new BufferedImage(w, h, type);
            Graphics2D g2 = tmp.createGraphics();
            g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, hint);
            g2.drawImage(ret, 0, 0, w, h, null);
            g2.dispose();

            ret = tmp;
        } while (w != targetWidth || h != targetHeight);

        return ret;
    }

(The above code is apparently present in the [SwingLabs code](http://javadoc.geotoolkit.org/external/swingx/org/jdesktop/swingx/graphics/GraphicsUtilities.html))

The article itself is from 2007, and I'm not up to date on the internal implementation of the drawImage function called in your code, so I figure'd I'd bring it up before making any pull requests or anything. Your thoughts?

**Comment by sksamuel** [comment]
I think its the same for fast scale. I think what that article is saying is that if you want an ok-quality scale, and something that's faster than a bilinear, you can use that technique. I don't think you'll get a faster scale than a nearest neighbour.

**Comment by EdgeCaseBerg** [comment]
And just to confirm, nearest neighbor is what scrimage is currently using?

**Comment by sksamuel** [comment]
I think that's the jdk default but we should check :)

**Comment by EdgeCaseBerg** [comment]
I imagine that the code calling: `g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_NEAREST_NEIGHBOR)` would make the jdk behave properly? I should have probably looked at the code again before commenting :)

**Comment by sksamuel** [comment]
I imagine that's the default but we should set it to be clear.

**Comment by EdgeCaseBerg** [comment]
There are a few places where it's not set to the default. Here's a quick grep to find a few: 

`grep "drawImage" ./* -r -B 2`

	./scrimage-core/src/main/scala/thirdparty/mortennobel/ImageUtils.java-    BufferedImage img = new BufferedImage(src.getWidth(), src.getHeight(), bufImgType);
	./scrimage-core/src/main/scala/thirdparty/mortennobel/ImageUtils.java-    Graphics2D g2d = img.createGraphics();
	./scrimage-core/src/main/scala/thirdparty/mortennobel/ImageUtils.java:    g2d.drawImage(src, 0, 0, null);
	--
	./scrimage-core/src/main/scala/com/sksamuel/scrimage/MutableAwtImage.scala-  protected[scrimage] def overlayInPlace(overlay: BufferedImage, x: Int = 0, y: Int = 0): Unit = {
	./scrimage-core/src/main/scala/com/sksamuel/scrimage/MutableAwtImage.scala-    val g2 = awt.getGraphics.asInstanceOf[Graphics2D]
	./scrimage-core/src/main/scala/com/sksamuel/scrimage/MutableAwtImage.scala:    g2.drawImage(overlay, x, y, null)
	--
	./scrimage-core/src/main/scala/com/sksamuel/scrimage/canvas/Drawable.scala-
	./scrimage-core/src/main/scala/com/sksamuel/scrimage/canvas/Drawable.scala-case class DrawableImage(imageToDraw: Image, x: Int, y: Int, context: Context = Context.Default) extends Drawable {
	./scrimage-core/src/main/scala/com/sksamuel/scrimage/canvas/Drawable.scala:  def draw(g: Graphics2D): Unit = g.drawImage(imageToDraw.awt, x, y, null)
	--
	./scrimage-core/src/main/scala/com/sksamuel/scrimage/AwtImage.scala-    val target = new BufferedImage(width, height, `type`)
	./scrimage-core/src/main/scala/com/sksamuel/scrimage/AwtImage.scala-    val g2 = target.getGraphics
	./scrimage-core/src/main/scala/com/sksamuel/scrimage/AwtImage.scala:    g2.drawImage(awt, 0, 0, null)
	--
	./scrimage-core/src/main/scala/com/sksamuel/scrimage/AwtImage.scala-    val g2 = target.getGraphics.asInstanceOf[Graphics2D]
	./scrimage-core/src/main/scala/com/sksamuel/scrimage/AwtImage.scala-    g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_NEAREST_NEIGHBOR)
	./scrimage-core/src/main/scala/com/sksamuel/scrimage/AwtImage.scala:    g2.drawImage(awt, 0, 0, targetWidth, targetHeight, null)
	--
	./scrimage-core/src/main/scala/com/sksamuel/scrimage/AwtImage.scala-    g2.translate(offset._1, offset._2)
	./scrimage-core/src/main/scala/com/sksamuel/scrimage/AwtImage.scala-    g2.rotate(angle)
	./scrimage-core/src/main/scala/com/sksamuel/scrimage/AwtImage.scala:    g2.drawImage(awt, 0, 0, null)
	--
	./scrimage-core/src/main/scala/com/sksamuel/scrimage/Filter.scala-  def apply(image: Image): Unit = {
	./scrimage-core/src/main/scala/com/sksamuel/scrimage/Filter.scala-    val g2 = image.awt.getGraphics.asInstanceOf[Graphics2D]
	./scrimage-core/src/main/scala/com/sksamuel/scrimage/Filter.scala:    g2.drawImage(image.awt, op, 0, 0)
	--
	./scrimage-core/src/main/scala/com/sksamuel/scrimage/Image.scala-    val target = new BufferedImage(awt.getWidth(null), awt.getHeight(null), `type`)
	./scrimage-core/src/main/scala/com/sksamuel/scrimage/Image.scala-    val g2 = target.getGraphics
	./scrimage-core/src/main/scala/com/sksamuel/scrimage/Image.scala:    g2.drawImage(awt, 0, 0, null)
	--
	./scrimage-core/src/main/scala/com/sksamuel/scrimage/composite/AlphaComposite.scala-    val g2 = src.awt.getGraphics.asInstanceOf[Graphics2D]
	./scrimage-core/src/main/scala/com/sksamuel/scrimage/composite/AlphaComposite.scala-    g2.setComposite(java.awt.AlphaComposite.SrcOver.derive(alpha.toFloat))
	./scrimage-core/src/main/scala/com/sksamuel/scrimage/composite/AlphaComposite.scala:    g2.drawImage(applicative.awt, 0, 0, null)
	--
	./scrimage-core/src/main/scala/com/sksamuel/scrimage/composite/composite.scala-    val g2 = src.awt.getGraphics.asInstanceOf[Graphics2D]
	./scrimage-core/src/main/scala/com/sksamuel/scrimage/composite/composite.scala-    g2.setComposite(BlendComposite.getInstance(mode, alpha.toFloat))
	./scrimage-core/src/main/scala/com/sksamuel/scrimage/composite/composite.scala:    g2.drawImage(applicative.awt, 0, 0, null)
	--
	./scrimage-filters/src/main/scala/thirdparty/marvin/image/MarvinImage.java-        Graphics2D g2d = (Graphics2D) buf.getGraphics();
	./scrimage-filters/src/main/scala/thirdparty/marvin/image/MarvinImage.java-        g2d.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
	./scrimage-filters/src/main/scala/thirdparty/marvin/image/MarvinImage.java:        g2d.drawImage(image, 0, 0, width, height, null);
	--
	./scrimage-filters/src/main/scala/thirdparty/marvin/image/MarvinImage.java-        Graphics2D g2d = (Graphics2D) buf.getGraphics();
	./scrimage-filters/src/main/scala/thirdparty/marvin/image/MarvinImage.java-        g2d.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
	./scrimage-filters/src/main/scala/thirdparty/marvin/image/MarvinImage.java:        g2d.drawImage(image, 0, 0, w, h, null);
	--
	./scrimage-filters/src/main/scala/thirdparty/misc/ThistleFilter.java-        //Blending Mode: Lighten, 55%
	./scrimage-filters/src/main/scala/thirdparty/misc/ThistleFilter.java-        gtmp2.setComposite(BlendComposite.getInstance(BlendComposite.BlendingMode.LIGHTEN, 0.55f));
	./scrimage-filters/src/main/scala/thirdparty/misc/ThistleFilter.java:        gtmp2.drawImage(tmp, 0, 0, bi.getWidth(), bi.getHeight(), null);
	--
	./scrimage-filters/src/main/scala/thirdparty/misc/ThistleFilter.java-        tmp = new BufferedImage(bi.getWidth(), bi.getHeight(), bi.getType());
	./scrimage-filters/src/main/scala/thirdparty/misc/ThistleFilter.java-        gtmp = tmp.createGraphics();
	./scrimage-filters/src/main/scala/thirdparty/misc/ThistleFilter.java:        gtmp.drawImage(texture, 0, 0, bi.getWidth(), bi.getHeight(), null);
	./scrimage-filters/src/main/scala/thirdparty/misc/ThistleFilter.java-        gtmp.setComposite(BlendComposite.getInstance(BlendComposite.BlendingMode.MULTIPLY, 0.75f));
	./scrimage-filters/src/main/scala/thirdparty/misc/ThistleFilter.java:        gtmp.drawImage(tmp2, 0, 0, bi.getWidth(), bi.getHeight(), null);
	--
	./scrimage-filters/src/main/scala/thirdparty/misc/ThistleFilter.java-        //Blending Mode: Overlay, 65%
	./scrimage-filters/src/main/scala/thirdparty/misc/ThistleFilter.java-        Graphics2D gdst = dstImg.createGraphics();
	./scrimage-filters/src/main/scala/thirdparty/misc/ThistleFilter.java:        gdst.drawImage(bi, 0, 0, null);
	./scrimage-filters/src/main/scala/thirdparty/misc/ThistleFilter.java-        gdst.setComposite(BlendComposite.getInstance(BlendComposite.BlendingMode.OVERLAY, 1f));
	./scrimage-filters/src/main/scala/thirdparty/misc/ThistleFilter.java:        gdst.drawImage(tmp, 0, 0, bi.getWidth(), bi.getHeight(), null);
	--
	./scrimage-filters/src/main/scala/thirdparty/misc/DaisyFilter.java-        //Blending Mode: Soft Light, 50%
	./scrimage-filters/src/main/scala/thirdparty/misc/DaisyFilter.java-        Graphics2D gdst = dstImg.createGraphics();
	./scrimage-filters/src/main/scala/thirdparty/misc/DaisyFilter.java:        gdst.drawImage(bi, 0, 0, null);
	./scrimage-filters/src/main/scala/thirdparty/misc/DaisyFilter.java-        gdst.setComposite(BlendComposite.getInstance(BlendComposite.BlendingMode.SCREEN, 0.6f));
	./scrimage-filters/src/main/scala/thirdparty/misc/DaisyFilter.java:        gdst.drawImage(changedColor, 0, 0, bi.getWidth(), bi.getHeight(), null);
	--
	./scrimage-filters/src/main/scala/thirdparty/jhlabs/image/TransitionFilter.java-            float t = minValue + transition * ( maxValue-minValue );
	./scrimage-filters/src/main/scala/thirdparty/jhlabs/image/TransitionFilter.java-			prepareFilter( t );
	./scrimage-filters/src/main/scala/thirdparty/jhlabs/image/TransitionFilter.java:            g.drawImage( src, filter, 0, 0 );
	--
	./scrimage-filters/src/main/scala/thirdparty/jhlabs/image/TransitionFilter.java-            float t = minValue + itransition * ( maxValue-minValue );
	./scrimage-filters/src/main/scala/thirdparty/jhlabs/image/TransitionFilter.java-			prepareFilter( t );
	./scrimage-filters/src/main/scala/thirdparty/jhlabs/image/TransitionFilter.java:            g.drawImage( destination, filter, 0, 0 );
	--
	./scrimage-filters/src/main/scala/thirdparty/jhlabs/image/ImageUtils.java-		BufferedImage p = new BufferedImage( image.getWidth(null), image.getHeight(null), BufferedImage.TYPE_INT_ARGB);
	./scrimage-filters/src/main/scala/thirdparty/jhlabs/image/ImageUtils.java-		Graphics2D g = p.createGraphics();
	./scrimage-filters/src/main/scala/thirdparty/jhlabs/image/ImageUtils.java:		g.drawImage( image, 0, 0, null );
	--
	./scrimage-filters/src/main/scala/thirdparty/jhlabs/image/ImageUtils.java-				for (y = y1; y < y2; y += h)
	./scrimage-filters/src/main/scala/thirdparty/jhlabs/image/ImageUtils.java-					for (x = x1; x < x2; x += w)
	./scrimage-filters/src/main/scala/thirdparty/jhlabs/image/ImageUtils.java:						g.drawImage(backgroundImage, x, y, c);
	--
	./scrimage-filters/src/main/scala/thirdparty/jhlabs/image/MotionBlurOp.java-        for ( int i = 0; i < steps; i++ ) {
	./scrimage-filters/src/main/scala/thirdparty/jhlabs/image/MotionBlurOp.java-            Graphics2D g = tmp.createGraphics();
	./scrimage-filters/src/main/scala/thirdparty/jhlabs/image/MotionBlurOp.java:            g.drawImage( tsrc, null, null );
	--
	./scrimage-filters/src/main/scala/thirdparty/jhlabs/image/MotionBlurOp.java-
	./scrimage-filters/src/main/scala/thirdparty/jhlabs/image/MotionBlurOp.java-            g.translate( cx+translateX, cy+translateY );
	./scrimage-filters/src/main/scala/thirdparty/jhlabs/image/MotionBlurOp.java:            g.scale( 1.0001+scale, 1.0001+scale );  // The .0001 works round a bug on Windows where drawImage throws an ArrayIndexOutofBoundException
	--
	./scrimage-filters/src/main/scala/thirdparty/jhlabs/image/MotionBlurOp.java-            g.translate( -cx, -cy );
	./scrimage-filters/src/main/scala/thirdparty/jhlabs/image/MotionBlurOp.java-
	./scrimage-filters/src/main/scala/thirdparty/jhlabs/image/MotionBlurOp.java:            g.drawImage( dst, null, null );
	--
	./scrimage-filters/src/main/scala/thirdparty/jhlabs/image/FeedbackFilter.java-        
	./scrimage-filters/src/main/scala/thirdparty/jhlabs/image/FeedbackFilter.java-		Graphics2D g = dst.createGraphics();
	./scrimage-filters/src/main/scala/thirdparty/jhlabs/image/FeedbackFilter.java:		g.drawImage( src, null, null );
	--
	./scrimage-filters/src/main/scala/thirdparty/jhlabs/image/FeedbackFilter.java-
	./scrimage-filters/src/main/scala/thirdparty/jhlabs/image/FeedbackFilter.java-            g.translate( cx+translateX, cy+translateY );
	./scrimage-filters/src/main/scala/thirdparty/jhlabs/image/FeedbackFilter.java:            g.scale( scale, scale );  // The .0001 works round a bug on Windows where drawImage throws an ArrayIndexOutofBoundException
	--
	./scrimage-filters/src/main/scala/thirdparty/jhlabs/image/FeedbackFilter.java-            g.translate( -cx, -cy );
	./scrimage-filters/src/main/scala/thirdparty/jhlabs/image/FeedbackFilter.java-
	./scrimage-filters/src/main/scala/thirdparty/jhlabs/image/FeedbackFilter.java:            g.drawImage( src, null, null );
	--
	./scrimage-filters/src/main/scala/thirdparty/jhlabs/image/DoGFilter.java-        Graphics2D g2d = image2.createGraphics();
	./scrimage-filters/src/main/scala/thirdparty/jhlabs/image/DoGFilter.java-        g2d.setComposite( new SubtractComposite( 1.0f ) );
	./scrimage-filters/src/main/scala/thirdparty/jhlabs/image/DoGFilter.java:        g2d.drawImage( image1, 0, 0, null );
	--
	./scrimage-filters/src/main/scala/com/sksamuel/scrimage/filter/BackgroundBlendFilter.scala-    val g = image.awt.getGraphics.asInstanceOf[Graphics2D]
	./scrimage-filters/src/main/scala/com/sksamuel/scrimage/filter/BackgroundBlendFilter.scala-    g.setComposite(getInstance(BlendingMode.ADD, 1f))
	./scrimage-filters/src/main/scala/com/sksamuel/scrimage/filter/BackgroundBlendFilter.scala:    g.drawImage(background.awt, 0, 0, null)
	--
	./scrimage-filters/src/main/scala/com/sksamuel/scrimage/filter/SnowFilter.scala-    val g2 = image.awt.getGraphics.asInstanceOf[Graphics2D]
	./scrimage-filters/src/main/scala/com/sksamuel/scrimage/filter/SnowFilter.scala-    g2.setComposite(new BlendComposite(BlendingMode.SCREEN, 1.0f))
	./scrimage-filters/src/main/scala/com/sksamuel/scrimage/filter/SnowFilter.scala:    g2.drawImage(scaled.awt, 0, 0, null)
	--
	./scrimage-filters/src/main/scala/com/sksamuel/scrimage/filter/SummerFilter.scala-    val g2 = image.awt.getGraphics.asInstanceOf[Graphics2D]
	./scrimage-filters/src/main/scala/com/sksamuel/scrimage/filter/SummerFilter.scala-    g2.setComposite(BlendComposite.getInstance(BlendComposite.BlendingMode.INVERSE_COLOR_BURN, 0.5f))
	./scrimage-filters/src/main/scala/com/sksamuel/scrimage/filter/SummerFilter.scala:    g2.drawImage(scaled.awt, 0, 0, null)
	--
	./scrimage-filters/src/main/scala/com/sksamuel/scrimage/filter/OldPhotoFilter.scala-
	./scrimage-filters/src/main/scala/com/sksamuel/scrimage/filter/OldPhotoFilter.scala-    val g2 = image.awt.getGraphics.asInstanceOf[Graphics2D]
	./scrimage-filters/src/main/scala/com/sksamuel/scrimage/filter/OldPhotoFilter.scala:    g2.drawImage(filtered, 0, 0, null)
	--
	./scrimage-filters/src/main/scala/com/sksamuel/scrimage/filter/OldPhotoFilter.scala-
	./scrimage-filters/src/main/scala/com/sksamuel/scrimage/filter/OldPhotoFilter.scala-    g2.setComposite(BlendComposite.getInstance(BlendComposite.BlendingMode.INVERSE_COLOR_DODGE, 0.30f))
	./scrimage-filters/src/main/scala/com/sksamuel/scrimage/filter/OldPhotoFilter.scala:    g2.drawImage(film.scaleTo(image.width, image.height).awt, 0, 0, null)
	--
	./scrimage-filters/src/main/scala/com/sksamuel/scrimage/filter/VignetteFilter.scala-    val g3 = image.awt.getGraphics.asInstanceOf[Graphics2D]
	./scrimage-filters/src/main/scala/com/sksamuel/scrimage/filter/VignetteFilter.scala-    g3.setComposite(new BlendComposite(BlendingMode.MULTIPLY, 1.0f))
	./scrimage-filters/src/main/scala/com/sksamuel/scrimage/filter/VignetteFilter.scala:    g3.drawImage(bg.awt, 0, 0, null)
	--
	./scrimage-filters/src/main/scala/com/sksamuel/scrimage/filter/VintageFilter.scala-    val filtered = thistle.filter(image.awt)
	./scrimage-filters/src/main/scala/com/sksamuel/scrimage/filter/VintageFilter.scala-    val g2 = image.awt.getGraphics.asInstanceOf[Graphics2D]
	./scrimage-filters/src/main/scala/com/sksamuel/scrimage/filter/VintageFilter.scala:    g2.drawImage(filtered, 0, 0, null)

**Comment by sksamuel** [comment]
drawImage(image,x,y,null) won't scale the image, but just render it pixel
by pixel (with optional composition).

**Comment by EdgeCaseBerg** [comment]
Just looking through the grep output, it looks like there's a few places where maybe it would be good to have the rendering hints? Example:

	./scrimage-filters/src/main/scala/thirdparty/misc/ThistleFilter.java-        tmp = new BufferedImage(bi.getWidth(), bi.getHeight(), bi.getType());
	./scrimage-filters/src/main/scala/thirdparty/misc/ThistleFilter.java-        gtmp = tmp.createGraphics();
	./scrimage-filters/src/main/scala/thirdparty/misc/ThistleFilter.java:        gtmp.drawImage(texture, 0, 0, bi.getWidth(), bi.getHeight(), null);
	./scrimage-filters/src/main/scala/thirdparty/misc/ThistleFilter.java-        gtmp.setComposite(BlendComposite.getInstance(BlendComposite.BlendingMode.MULTIPLY, 0.75f));
	./scrimage-filters/src/main/scala/thirdparty/misc/ThistleFilter.java:        gtmp.drawImage(tmp2, 0, 0, bi.getWidth(), bi.getHeight(), null);

Since it's calling the 5 parameter version of drawImage it will do some scaling right?

**Comment by sksamuel** [comment]
@EdgeCaseBerg I don't think it matters in that case as the output dimensions are the same as the input dimensions. So it shouldn't scale anything.

I've added a custom implementation of nearest neighbour for scaling down, which seems to be 75-10% faster than AWT depending on the output ratio.

Testing scale from 6400,3200 to 300,200
AWT:
Total time: 652
Average time: 6

Scrimage:
Total time: 46
Average time: 0
-----
Testing scale from 6400,3200 to 1000,600
AWT:
Total time: 703
Average time: 6

Scrimage:
Total time: 156
Average time: 1
-----
Testing scale from 6400,3200 to 2000,1200
AWT:
Total time: 1173
Average time: 11

Scrimage:
Total time: 500
Average time: 4
-----
Testing scale from 6400,3200 to 3200,1600
AWT:
Total time: 1863
Average time: 18

Scrimage:
Total time: 1023
Average time: 10
-----
Testing scale from 6400,3200 to 6000,3000
AWT:
Total time: 5032
Average time: 49

Scrimage:
Total time: 3611
Average time: 35
-----

See NearestNeighbourBenchmark in master.

**Comment by EdgeCaseBerg** [comment]
Awesome, thanks for being so thorough!
