### ISSUE TITLE
Image.fromFile doesn't call IphoneOrientation.reorient

### ISSUE THREAD

**Issue by fredfp** [sksamuel/scrimage#88]
The doc says:
`Note: This will only work if you use Image.fromStream, Image.fromResource, or Image.fromFile, as otherwise the metadata will not be available`

And from the code it seems `Image.fromFile` doesn't do that.

I also have the feeling `def apply(bytes: Array[Byte])` could benefit from `IphoneOrientation.reorient`

**Comment by sksamuel** [comment]
I'll check and fix for fromFile. We can't do it for fromBytes as raw bytes don't have the image metadata attached.

**Comment by fredfp** [comment]
Why not?
According to the document of the `def apply(bytes: Array[Byte])` method, it doesn't expect pixels but an image format. I usually pass png/jpg data to it and it works.

**Comment by sksamuel** [comment]
Because the meta data is read from another library which only works on
files.

**Comment by fredfp** [comment]
ok, seeing that it works with `Image.fromStream` I thought wrapping the bytes in an `InputStream` would do the trick.

Thanks for your time, and thanks for scrimage!

**Comment by sksamuel** [comment]
Thanks @fredfp  I've update the apply method to include metadata now.
