### ISSUE TITLE
Can't compile a project with import

### ISSUE THREAD

**Issue by sergeda** [sksamuel/scrimage#90]
With this line in code import com.sksamuel.scrimage._ I am getting error "object sksamuel is not a member of package com". How come? What I'm doing wrong?

**Comment by sksamuel** [comment]
Can we see more of your project? Sounds like a dependency issue.

**Comment by sergeda** [comment]
Here is my dependency:

**Comment by sksamuel** [comment]
That's blank :)

**Comment by sksamuel** [comment]
But what I mean is, need to see your entire project as it sounds like an IDE / SBT issue etc.

**Comment by sergeda** [comment]
Oh, never mind. I've restarted Play Framework activator console and problem have gone. Sorry for bother you
