### ISSUE TITLE
AwtImage.rotate - suggested changes

### ISSUE THREAD

**Issue by Hivemind9000** [sksamuel/scrimage#91]
Just a suggestion. The rotate function is not exposed (in the Image class), and when I did expose it, it didn't work that well (it seemed to rotate around an arbitrary coordinate). My preference was that it rotated about the center of the image by default (like your rotateLeft and rotateRight methods). After a bit of investigation, the following code handles the rotateLeft and rotateRight as well as other angles.

Also, changed the "in degrees" to "in radians", and also the parameter from "angle" to "radians" (which helps with understanding the method requirements without having to read the code).

Cheers,

Darren

```
/**
   * Returns a new AWT Image rotated with the given angle (in radians)
   */
  protected[scrimage] def rotate(radians: Double): BufferedImage = {
    val target = new BufferedImage(height, width, awt.getType)
    val g2 = target.getGraphics.asInstanceOf[Graphics2D]
    g2.translate(width / 2, height / 2)
    g2.rotate(radians)
    g2.translate(- width / 2, - height / 2)
    g2.drawImage(awt, 0, 0, null)
    g2.dispose()
    target
  }
```

**Comment by sksamuel** [comment]
Thanks for the suggestion. When I try using this code, the translation of the rotateLeft and rotateRight gets messed up. You can see that in the ImageTest if you want to try.
