### ISSUE TITLE
Image is not rotated

### ISSUE THREAD

**Issue by virtu0zz0** [sksamuel/scrimage#93]
Image is not rotated if it contains two orientation tags. Here the exif details:

(3)  = {Directory@1788} "Directory(Exif IFD0,List(Tag(Make,271,Sony,Sony), Tag(Model,272,C6903,C6903), Tag(Orientation,274,6,Right side, top (Rotate 90 CW)), Tag(X Resolution,282,72,72 dots per inch), Tag(Y Resolution,283,72,72 dots per inch), Tag(Resolution Unit,296,2,Inch), Tag(Software,305,14.5.A.0.270_6_f100000f,14.5.A.0.270_6_f100000f), Tag(Date/Time,306,2015:09:08 11:54:11,2015:09:08 11:54:11), Tag(YCbCr Positioning,531,1,Center of pixel array)))"
(5)  = {Directory@1792} "Directory(Exif Thumbnail,List(Tag(Thumbnail Compression,259,6,JPEG (old-style)), Tag(Orientation,274,6,Right side, top (Rotate 90 CW)), Tag(X Resolution,282,72,72 dots per inch), Tag(Y Resolution,283,72,72 dots per inch), Tag(Resolution Unit,296,2,Inch), Tag(Thumbnail Offset,513,12408,12408 bytes), Tag(Thumbnail Length,514,7121,7121 bytes)))"

And the image: 
![55eea23be4b0df33dfb389ed](https://cloud.githubusercontent.com/assets/5426471/9732170/5f9b3bbc-562a-11e5-8d33-4534d2b54c18.jpg)

As an output I have an image that is not rotated and worse image loses all exif data so image viewers cannot rotate image automatically

**Comment by sksamuel** [comment]
Ok so I made it ignore rotation if there's 2, as there were some iphones putting contradictory information in, but I think I could make it so that if there's multiple, but the same, then it acts on it.
