### ISSUE TITLE
Rename scrimage-io in documentation as well

### ISSUE THREAD

**Issue by denisrosset** [sksamuel/scrimage#94]
Hey,

libraryDependencies += "com.sksamuel.scrimage" %% "scrimage-io" % "2.1.0"

should read

libraryDependencies += "com.sksamuel.scrimage" %% "scrimage-io-extra" % "2.1.0"

in the README and possibly in other places.

(and thanks for this very good library)

**Comment by ogeagla** [comment]
I just fixed this in https://github.com/sksamuel/scrimage/pull/95
