### ISSUE TITLE
scalajs support

### ISSUE THREAD

**Issue by antonkulaga** [sksamuel/scrimage#96]
I know that it is not an easy task but it would be wonderful to be able to use it in ScalaJS as basic image operations are common for the web (things like scaling userpics or croping photos before uploading)

**Comment by gwenzek** [comment]
I started last year a branch where I was removing Java.awt, which I think
would be the greatest obstacle to a scala - js support.

I don't know the images interfaces available in scala-js. But it's worth
looking into.

It's a long time I didn't check my code and it's now well behind the master
branch but it may still be useful.

**Comment by sksamuel** [comment]
It's a nice idea, but would mean replacing AWT with a Javascript compatible layer, and I'm afraid that's well beyond the scope of this library.
