### ISSUE TITLE
Documentation on Image Scaling Uses the Wrong Method

### ISSUE THREAD

**Issue by Perif** [sksamuel/scrimage#97]
The documentation on image scaling below uses :

    val in = ... // input stream
    val out = ... // output stream
    Image.fromStream(in).scale(300, 200, FastScale)

It should be :

    val in = ... // input stream
    val out = ... // output stream
    Image.fromStream(in).scaleTo(300, 200, FastScale)

**Comment by sksamuel** [comment]
Thanks,

**Comment by Perif** [comment]
You are welcome.
