### ISSUE TITLE
Working with a large number of files - closing files

### ISSUE THREAD

**Issue by ksilin** [sksamuel/scrimage#98]
I am trying to process several million images in a batch. However, the batches die unexpectedly because of too many open files. AFAICT, the `InputStream` created in `Image#fromPath` is not being closed. 

My workaround now is a `using` on a structural type with a `close()`.

Are you OK with a PR on that?

**Comment by sksamuel** [comment]
Please do, should be being closed my bad.

**Comment by sksamuel** [comment]
Will release 2.1.3 with these fixes
